---
title: "test"
author: 'Dolf Andringa'
date: "February 7, 2016"
output:
  html_document:
    fig_caption: yes
    keep_md: yes
    number_sections: no
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: true
---
```{r getdata, results=FALSE, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
#load("samples.RDa")
test=data.frame(index=1:52, states=1:52)
library(knitr)
```
# Methods

.... some explanation

# Results

```{r, echo=FALSE, results='asis'}
res <- knitr::knit_child('child.Rmd', quiet = TRUE)
cat(res, sep = '\n')
```


```{r echo=FALSE, eval=FALSE, include=FALSE}
out <- NULL
for(sg in 1:4){
  print(sg)
  specnum<-0
  #for(sp in sort(species[species$species_group==sg,]$species_colname)){
  #  sp<-sp #update the sp variable in the environment
  #  sp.common<-species[species$species_colname==sp,c("common_name")] #update the sp.common variable in the environment
    env=new.env() #create a new empty environment, it inherits objects from the current environment.
    out <- c(out, knit_child('child.Rmd', envir=env))
  } 
```
`r paste(out, collapse='\n')`