\documentclass{article}
\usepackage{hyperref}

\author{Marc Los Huertos}
\title{Citing Sources in EA30}

\begin{document}
\maketitle

\section{Why Cite Sources?}

Citing sources is how we enter a scholarly conversation -- it's also how we provide evidence or counter evidence for an arugement. 

\section{Author-Year: Claims about what is important}

By documenting our sources as author-year we are implicitly identifying two "signifyiers" where the author's creditials 
are important and that the year has some significance. By using this method, readers can immeidiately recognize (if they are also scholars o fthe topic) that you are engaging the appropriate authors. 

Warning: If you are citing the wrong person, it will set you back in the mind of the reader!

\section{Selecting a Consistent Style}

There are many styles used reference your sources. These include familiar ones, such as the "APA" (American Pyschology Assocation) and "MLPA" (Langage and XX Assocation).

For our purposes, we will rely on the guidelines set up the the Council of Scientific Editors (CSE) method. 

\section{Implementing CSE}

There are a number of sources for this citation format. Here are some good sources that can help:

\href{https://writing.wisc.edu/Handbook/DocCSE_NameYear.html}{The Writer's Handbook: 
CSE Name-Year Documentation, University of Wisconsin}

\subsection{In-line Citation Format}

The rapid discovery of the unique mechanisms underlying crown gall disease demonstrated how quickly 
an area could advince given significant investment and competition (Zambryski 1988).

When there are two ahthors, the format changes abit: 

Initial infection of tubers by H. solani occurs in the field either from the seed tuber 
(Jellis and Taylor 1977) or soil (Merida and Loria 1994).

\subsection{In-line Citations -- Multiple Authors}

Similarly, a series of epidemiological studies of P. syringae as a bean epiphyte and pathogen by Hirano and Upper 
laid the foundation for elegant experiments showing that type III secreted effectors and the Gac regulon are each 
critical for epiphytic fitness in the field; these important phenotypes were invisible in the controlled environment 
of a growth chamber (Upper and Hirano 1996; Hirano et al. 1997, 1999).

\subsection{In-line Quotes}

Quoted text requires that the page number be identified: 

Farmers participating in these knowledge networks, Hassanein writes, "challenged the power relations in agricultural knowledge 
production and distribution by relying on their own and members' experiential knowledge" (Hassanein 1997, 304).

Similarly, Hayward, Simpson, and Wood (2004:95) describe "a mythologizing of the power of participatory methodologies to accomplish 
problem solving, emancipation or empowerment."

\subsection{Bibliography Format}

Allen C, Prior P, Hayward AC. 2005. Bacterial wilt: the disease and the Ralstonia solanacearum species complex. 
St. Paul (MN): APS Press 508 p.

Flores-Cruz Z, Allen C. 2011. Necessity of OxyR for the hydrogen peroxide stress response and full virulence in Ralstonia solanacearum. 
Appl Environ Microbiol. 77(18):6426-6432.

Bennett AB, Gratton C. 2013. Floral diversity increases beneficial arthropod richness and decreases variability in arthropod community composition. 
Ecol Appl [Internet]. [cited 12 Sep 2013];23(1):86-95. 
Available from: http://labs.russell.wisc.edu/gratton/files/2013/03/Ecological-Applications.pdf

ASAP: systematic annotation package for community analysis of genomes [Internet]. 2013. Madison (WI): University of Wisconsin-Madison; [cited 2013 Sep 12]. 
Available from http://www.genome.wisc.edu/tools/asap.htm


Note: There is no period when for URLs but there are for the prior part of the citation.

\section{Reference Libraries}

\subsection{Endnote}

\subsection{Zootero}

\subsection{Jabref}

\subsection{Mendeley}

\subsection{Refworks}

\section{Integrating Word Processors and Cited References}

\subsection{Endnote and Word}

\subsection{\LaTeX and Jabref}

\subsection{Mendeley and Word}

\end{document}
