- Arizona has warmed about two degrees (F) in the last century. 
- Throughout the southwestern United States, heat waves are becoming more common, and snow is melting earlier in spring. - In the coming decades, changing the climate is likely to decrease the flow of water in the Colorado River, threaten the health of livestock, increase the frequency and intensity of wildfires, and convert some rangelands to desert.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-az.pdf)

## State Adaptation / Mitigation Plans

- Arizona has not developed a statewide adaptation plan. 

- Arizona Climate and Health Adaptation Plan 2017	Public health	April 2017

- Arizona DOT Resilience Pilot Program	Emergency preparedness, Transportation	August 2015

- Arizona Extreme Weather, Climate and Health Profile Report	Public health, Frontline Communities	March 2015

- Preliminary Study of Climate Adaptation for the Statewide Transportation System in Arizona	Emergency preparedness, Land use and built environment, Transportation	March 2013

- Arizona Wildlife Action Plan 2012-2022	Biodiversity and ecosystems, Wildlife	May 16, 2012

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/arizona/overview.html)