---
title: "Draft Blog"
author: "Valentina Emanuele"
date: "9/18/2017"
output: html_document
---

```{r setup, include=FALSE}
#climate_data <- read.csv("Student_Folders/Valentina/valentina_cmont_data.csv")

climate_data <- read.csv("/home/CAMPUS/veja2016/Climate_Change_Narratives/Student_Folders/Valentina/valentina_cmont_data.csv")
#str(climate_data)
climate_data$TMAX[climate_data$TMAX==-9999] = NA
climate_data$TMIN[climate_data$TMIN==-9999] = NA
climate_data$NewDate <- as.Date(NA, "%Y-%m-%d")
strDates <- as.character(climate_data$DATE)
climate_data$NewDate[1:2484] <- as.Date(strDates[1:2484], "%Y-%m-%d")
climate_data$NewDate[2485:38063] <- as.Date(strDates[2485:38063], "%m/%d/%Y")
```



## Temperature Data in Claremont, CA


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(TMAX ~ NewDate, climate_data)

climate_data.lm <- lm(TMAX~NewDate, climate_data)
abline(coef(climate_data.lm), col='red')



```


```{r echo=FALSE}

climate_data$Month = format(as.Date(climate_data$NewDate), format = "%m") 
climate_data$Year = format(climate_data$NewDate, format="%Y")

MonthlyTMAXMean = aggregate(TMAX ~ Month + Year, climate_data, mean)

MonthlyTMAXMean$YEAR = as.numeric(MonthlyTMAXMean$Year) 
MonthlyTMAXMean$MONTH = as.numeric(MonthlyTMAXMean$Month) 

str(MonthlyTMAXMean)

MonthlyTMAXSD = aggregate(TMAX ~ Month + Year, climate_data, sd)

MonthlyTMAXSD$YEAR = as.numeric(MonthlyTMAXSD$Year) 
MonthlyTMAXSD$MONTH = as.numeric(MonthlyTMAXSD$Month) 
MonthlyTMAXSD$NewDate = MonthlyTMAXSD$YEAR + (MonthlyTMAXSD$MONTH - 1)/12

head(MonthlyTMAXSD)

plot(MonthlyTMAXMean$TMAX, ty='l')

plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="08",], ty='p', xlim=c(1950, 2020)) 
Aug.lm <- lm(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="08",])

abline(coef(Aug.lm), col='red')

summary(Aug.lm)


```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
