## Impacts

- The `r files$State` has not become warmer over the last 50 years, but we expect `r files$State` to become warmer in the coming decades.
- The state will probably experience more severe floods and drought, where more rain arrives in heavy downpours with associated flooding.
<!-- - As another example of counter-intuitive results, `r files$State`'s soils have become drier, while annual rainfall has increased in most of the state.  -->
- Sea level has been rising about one inch every eight years, which will have huge impacts on infastructure in the coastal zone. 
- Changing the climate is likely to increase damages from tropical storms, reduce crop yields, harm livestock, increase the number of unpleasantly hot days, increase the risk of heat stroke and other heat-related illnesses.
- [Source: EPA Snapshot (2017)](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-al.pdf)

## State Adaptation / Mitigation Plans
 
- Alabama has not developed a statewide adaptation plan.
- Impacts of Climate Change and Variability on Transportation Systems and Infrastructure: The Gulf Coast Study, Phase 2 (Mobile, Alabama)
- [Source: Georgetown Climate Center](https://www.georgetownclimate.org/adaptation/state-information/alabama/overview.html)