## Impacts

- Loss of glaciers and sea ice
- Melting of permafrost and disruption of infrastructure, and increase costs of energy production
- Impact on fisheries and wildlife
- Changes in forest resources and loss of tundra carbon storage
- Profound impact on Alaska Native Communities
- Probably impacts on health and well-being of vulnerable peoples
    
[EPA Snapshot (2017)](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-ak.pdf)

## State Adaptation / Mitigation Plans

- On September 14, 2007, Governor Sarah Palin established the Alaska Climate Change Sub-Cabinet to advise the Office of the Governor in preparing and implementing a climate change strategy for the state (Administrative Order No. 238).
- An Adaptation Advisory Group was responsible for developing recommendations to address impacts of climate change in Alaska, and submitted its recommendations to the Sub-Cabinet on January 27, 2010. 
- The final 2010 plan, Alaska's Climate Change Strategy: Addressing Impacts in Alaska (Strategy), recommends a variety of steps to address the current and anticipated impacts of climate change

[Source: Georgetown Climate Center](https://www.georgetownclimate.org/adaptation/state-information/alaska/overview.html)