## Impacts

- California’s climate is changing. 
- Southern California has warmed about three degrees (F) in the last century
and all of the state is becoming warmer. 
- Heat waves are becoming more common, snow is melting earlier in
spring—and in southern California, less rain is falling
as well. 
- In the coming decades, the changing climate is likely to further decrease the supply of water, increase
the risk of wildfires, and threaten coastal development
and ecosystems
- [Source: EPA Snapshot (2017)](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-ca.pdf)

## State Adaptation / Mitigation Plans

- California is engaged in both directly planning for climate impacts and incorporating climate adaptation into its existing policies and programs. 
- On November 14, 2008, Governor Arnold Schwarzenegger called on the California Natural Resources Agency (CNRA) to develop a state Climate Adaptation Strategy in coordination with public and private entities at the local, regional, state and federal levels (Executive Order S-13-08). 
- CNRA organized state agencies into seven resource-based sector working groups. Each working group identified both short- and long-term adaptation goals and a process for reporting on progress.
- [Source: Georgetown Climate Center](https://www.georgetownclimate.org/adaptation/state-information/california/overview.html)