## Impacts

- Colorado’s climate is changing. 
- Most of the state has warmed one or two degrees (F) in the last century, but some areas including the station analyzed here does not show that pattern. 
- Throughout the western United States, heat waves are becoming more common, snow is melting earlier in spring, and less water flows through the Colorado River. 
- Rising temperatures and recent droughts in the region have killed many trees by drying out soils, increasing the risk of forest fires, or enabling outbreaks of forest insects. 
- In the coming decades, the changing climate is likely to decrease water availability and agricultural yields in Colorado, and further increase the risk of wildfires
- [Source: EPA Snapshot (2017)](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-co.pdf)

## State Adaptation / Mitigation Plans (needs updating!)

- On November 5, 2007, Governor Bill Ritter called on the state to prepare for and adapt to climate changes that cannot be avoided and the state released the Colorado Climate Action Plan: A Strategy to Address Global Warming.
- On April 22, 2008, Governor Ritter created the state's Climate Change Advisory Panel and called on the panel to make recommendations on how the state could achieve the goals of Colorado's Climate Action Plan, including by developing adaptation strategies (Executive Order B007 08).
- [Source: Georgetown Climate Center](https://www.georgetownclimate.org/adaptation/state-information/colorado/overview.html)