## Impacts

- The District of Columbia’s climate is changing. 
- The region has warmed by more than two degrees (F) in
the last century, hot days and heavy rainstorms are more frequent, and the tidal Potomac is rising about one inch every eight years. 
- In the coming decades, changing climate is likely to increase tidal flooding, cause more heavy rainstorms and sewer overflows, and increase some risks to human health. 
- [Source: EPA Snapshot (2016)](https://19january2017snapshot.epa.gov/sites/production/files/2016-11/documents/climate-change-dc.pdf)

## State Adaptation / Mitigation Plans

- In January 2013, Mayor Vincent Gray signed the Sustainable DC Act of 2012, which was enacted along with the release of the District's comprehensive sustainability plan, Sustainable DC. 
<!-- - Then, on July 29, 2014, Mayor Gray signed into law the Sustainable DC Omnibus Amendment Act of 2014. That law articulates the Mayor’s vision to make the District of Columbia, in one generation, “the healthiest, greenest, and most livable city in the United States.” The components of the 2014 Sustainable DC Act are meant to further the goals prioritized in the Sustainable DC plan.  -->
- The District released its final Sustainable DC 2.0 Plan in April 2019. The Sustainable DC plans present a holistic approach to promoting sustainability across many sectors in the District of Columbia, including climate adaptation planning principles. 
- Sustainable DC 2.0 includes sustainability actions presented under 13 focal topics including: Governance, Equity, Built Environment, Climate, Economy, Education, Energy, Food, Health, Nature, Transportation, Waste, and Water.In 2013 the District of Columbia Department of Transportation has developed a Climate Change Adaptation Plan.
- [Source: Georgetown Climate Center](https://www.georgetownclimate.org/adaptation/state-information/district-of-columbia/overview.html)