## Impacts

- Florida's climate is changing. 
- The Florida peninsula has warmed more than one degree (F) during the last century. 
- The sea is rising about one inch every decade, and heavy rainstorms are becoming more severe. 
- In the coming decades, rising temperatures are likely to increase storm damages, harm coral reefs,
increase the frequency of unpleasantly hot days, and reduce the risk of freezing to Florida's agriculture.
    
[Source: EPA Snapshot (2016)](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-fl.pdf)

## State Adaptation / Mitigation Plans

- On July 13, 2007, Governor Charlie Crist established the Florida Governor’s Action Team on Energy and Climate Change and directed it to create a comprehensive Energy and Climate Change Action Plan (Executive Order 07-128). 
- The executive order directed that the Action Plan include strategies to reduce greenhouse gas emissions and, in a second phase, long-term strategies for reducing climate impacts to society, public health, the economy, and the natural environment. 
- Six work groups were formed to develop recommendations for the Action Plan, including the Adaptation Technical Work Group, which was responsible for developing the adaptation portion of the Action Plan

[Source: Georgetown Climate Center](https://www.georgetownclimate.org/adaptation/state-information/florida/overview.html)