## Impacts

- In the coming decades, changes in the earth's atmosphere are likely to alter several aspects of life in Guam. 

- The air and ocean are warming, sea level is rising, and the ocean is becoming more acidic. 

- These changes are likely to damage or destroy much of Guam’s coral reef ecosystems, increase damages from flooding and typhoons, reduce the availability of fresh water during the dry season, and make air temperatures uncomfortably hot more often than they are today.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-gu.pdf)

## Impacts

- East-West Center has a most more detailed discussion on the impacts on Guam. 

- Average Temperatures have increase.

- Hot days have increased.

- Cold days have decreased.

- Extreme rain fall events increased.

[Climate Change in Guam: Indicators and Considerations for Key Sectors
by  Zena Grecni, Wendy Miles, Romina King, Abby Frazier, and Victoria Keener
November 9, 2020](https://www.eastwestcenter.org/system/tdf/private/climate-change-in-guam-pirca-2020-low-res.pdf?file=1&type=node&id=38766)

## State Adaptation / Mitigation Plans

- Unable to find a comprehensive adapation / mitigation plan for Guam.

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/guam/overview.html)