## Impacts

- Hawaii's climate is changing. In the last century, air temperatures have increased between one-half and one
degree (F). 

- Average precipitation decreased in the last century, reducing freshwater availability and affecting delicate land-based ecosystems, often harming native species. 

- Warming in the oceans around Hawaii has damaged coral reefs, and increased ocean acidity has threatened reefs and other marine ecosystems. 
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-hi.pdf)

## State Adaptation / Mitigation Plans (needs updating!)

- Hawaii has not yet adopted an official statewide adaptation plan, however, the state legislature has called for adaptation planning and state agencies have undertaken other efforts to assess climate vulnerabilities and identify adaptation strategies.

- On June 9, 2014, Hawaii Governor Neil Abercrombie signed House Bill 1714 (now Act 83) establishing an Interagency Climate Adaptation Committee charged with developing a sea-level rise vulnerability and adaptation report addressing statewide impacts through 2050. 

- In 2017, the state legislature passed Senate Bill 559 that renamed the Adaptation Committee as the Hawaii Climate Change Mitigation and Adaptation Commission. 

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/hawaii/overview.html)