## Impacts

- Idaho's climate is changing. Over the past century, most of the state has warmed one to two degrees (F).

- Snowpack is melting earlier in the year, and the flow of meltwater into streams during summer is declining. 

- In the coming decades, streams will be warmer, populations of several fish species may decline, wildfires may be more common, deserts may expand, and water may be less available for irrigation.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-az.pdf)

## State Adaptation / Mitigation Plans

- Idaho has not developed a statewide adaptation plan. Other resources from the Adaptation Clearinghouse, which have been developed by the state and localities to help communities prepare for climate change such as:

- Boise, Idaho - Boise's Climate Action Roadmap, 2021

- Nez Perce Tribe Clearwater River Subbasin Climate Change Adaptation Plan, December 30, 2011

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/arizona/overview.html)