## Impacts

- Illinois's climate is changing. Most of the state has warmed by about one degree (F) in the last century. 

- Floods are becoming more frequent, and ice cover on the Great Lakes is forming later or melting sooner. 

- In the coming decades, the state will have more extremely hot days, which may harm public health in urban areas and corn harvests in rural areas.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-il.pdf)

## State Adaptation / Mitigation Plans

- Illinois has not developed a statewide adaptation plan. Other resources from the Adaptation Clearinghouse, which have been developed by the state and localities to help communities prepare for climate change, such as:

- State of Illinois Drought Preparedness and Response Plan	Rural, Water resources	October 12, 2011

- Adapting Conservation to a Changing Climate: An Update to the Illinois Wildlife Action Plan	Biodiversity and ecosystems, Fish and fisheries, Wildlife	May 11, 2011

- Illinois SB 1489: Green Infrastructure for Clean Water Act	Biodiversity and ecosystems, Land use and built environment, Water resources	June 30, 2009

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/illinois/overview.html)