## Impacts

- Iowa's climate is changing. 

- Most of the state has warmed one-half to one degree (F) in the last century, and floods are becoming
more frequent. 

- In the coming decades, the state will have more extremely hot days, which may harm public health in urban areas and corn harvests in rural areas.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-ia.pdf)

## State Adaptation / Mitigation Plans

- Iowa has not developed a statewide adaptation plan. Other resources from the Adaptation Clearinghouse, which have been developed by the state and localities to help communities prepare for climate change, such as:

- Iowa Wildlife Action Plan - Securing a Future for Fish and Wildlife: A Conservation Legacy for Iowans	Biodiversity and ecosystems, Fish and fisheries, Land management and conservation, Wildlife	2015

- Climate Change Impacts on Iowa 2010	Assessments	January 1, 2011

- Iowa Climate Change Adaptation and Resilience Report	Planning	2011

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/iowa/overview.html)