## Impacts

- Kentucky's climate is changing. 

- Although the average temperature did not change much during the 20th century, most of the commonwealth has warmed in the last  20 years. 
- Average annual rainfall is increasing, and a rising percentage of that rain is falling on the four wettest days of the year. 

- In the coming decades, the changing climate is likely to reduce crop yields and threaten some aquatic ecosystems. 

- Floods may be more frequent, and droughts may be longer, which would increase the difficulty of meeting the competing demands for water in the Ohio, Tennessee, and Cumberland rivers.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-ky.pdf)

## State Adaptation / Mitigation Plans

- Kentucky has not developed a statewide adaptation plan. 

- Other resources from the Adaptation Clearinghouse, which have been developed by the state and localities to help communities prepare for climate change, such as: 

- Action Plan to Respond to Climate Change in Kentucky: A Strategy of Resilience (KY Wildlife Action Plan)	Biodiversity and ecosystems, Fish and fisheries, Wildlife	2010

- Louisville Urban Heat Management Study	April 2016

- Louisville Urban Tree Canopy Assessment	March 1, 2015


[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/kentucky/overview.html)