## Impacts

- In the coming decades, Louisiana will become warmer, and both f loods and droughts may become more severe. Unlike most of the nation, Louisiana did not become warmer during the last century. But soils have become drier, annual rainfall has increased, more rain arrives in heavy downpours, and sea level is rising. Our changing climate is likely to increase damages from floods, reduce crop yields and harm fisheries, increase the number of unpleasantly hot days, and increase the risk of heat stroke and other heat-related illnesses.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-la.pdf)

## State Adaptation / Mitigation Plans

- Louisiana has not developed a statewide adaptation plan. Other resources from the Adaptation Clearinghouse, which have been developed by the state and localities to help communities prepare for climate change, such as:

Louisiana Executive Order Number JBE 2020-19 on Coastal Resilience	Law and Governance	August 19, 2020
Louisiana Watershed Initiative	Planning	August 15, 2018

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/louisiana/overview.html)