## Impacts

- Maine's climate is changing. 

- The state has warmed about three degrees (F) since the year 1900. 

- Throughout the northeastern United States, spring is arriving earlier and bringing more precipitation, heavy rainstorms are more frequent, and summers are hotter and drier. 

- Sea level is rising, and severe storms increasingly cause floods that damage property and infrastructure. 
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-me.pdf)

## State Adaptation / Mitigation Plans (needs updating)

- In 2003, the Maine Legislature charged the Department of Environmental Protection (DEP) with developing a mitigation plan to reduce greenhouse gas emissions (H.P. 622 — L.D. 845, An Act To Provide Leadership in Addressing the Threat of Climate Change). This directive led to the development of the 2004 Maine Climate Action Plan.

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/maine/overview.html)