## Impacts

- Maryland's climate is changing. 

- Most of the state has warmed one to two degrees (F) in the last century, heavy rainstorms are more frequent, and the sea is rising about one inch every seven to eight years. 

- Higher water levels are eroding beaches, submerging low lands, exacerbating coastal flooding, and increasing the salinity of estuaries and aquifers. 

- In the coming decades, changing the climate is likely to increase coastal and inland flooding; harm marine, wetland, and inland ecosystems; disrupt fishing and farming; and increase some risks to human health.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-md.pdf)

## State Adaptation / Mitigation Plans

- On April 20, 2007, Governor Martin O'Malley established the Maryland Commission on Climate Change and directed the Commission to create a Climate Action Plan including measures to reduce greenhouse gas emissions and prepare for the impacts of climate change (Executive Order 01.01.2007.07). 

- Maryland developed two climate change adaptation plans: a Comprehensive Strategy for Reducing Maryland's Vulnerability to Climate Change, Phase I: Sea-level rise and coastal storms (Chapter 5 of the Climate Action Plan; ''2008 Plan'') and a Comprehensive Strategy for Reducing Maryland's Vulnerability to Climate Change, Phase II: Building societal, economic, and ecological resilience, published on January 24, 2011 (''2011 Plan''). 

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/maryland/overview.html)