## Impacts

- The climate of Massachusetts is changing. 

- The commonwealth has warmed by more than two degrees (F) in the last century. 

- Throughout the northeastern United States, spring is arriving earlier and bringing more precipitation, heavy rainstorms are more frequent, and summers are hotter and drier. 

- Sea level is rising, and severe storms increasingly cause floods that damage property and infrastructure. 
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-ma.pdf)

## State Adaptation / Mitigation Plans

- Massachusetts first completed a Climate Protection Plan in 2004 to address climate mitigation goals. 

- In 2008, the Secretary of Energy and Environmental Affairs convened an Adaptation Advisory Committee under the Global Warming Solutions Act (Section 9) to develop strategies for adapting to predicted changes to the climate. 

- The Adaptation Advisory Committee members represented 12 sectors and focus areas. The committee's final report, Massachusetts Climate Change Adaptation Report was published in September 2011 and provides an overview of climate change impacts in Massachusetts, specific vulnerabilities in multiple sectors and explicit climate adaptation goals.

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/massachusetts/overview.html)