## Impacts

- Michigan's climate is changing. 

- Most of the state has warmed two to three degrees (F) in the last century. 

- Heavy rainstorms are becoming more frequent, and ice cover on the Great Lakes is forming later or melting sooner. 

- In the coming decades, the state will have more extremely hot days, which may harm public health in urban areas and corn harvests in rural areas.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-mi.pdf)

## State Adaptation / Mitigation Plans

- In November 2007, Governor Jennifer M. Granholm issued Executive Order No. 2007-42 establishing the Michigan Climate Action Council and calling for the development of a state Climate Action Plan. 

- In March 2009, the Council released the Michigan Climate Action Plan focusing mainly on efforts the state can take to reduce carbon pollution, but also recognizing the risks that climate change will pose to the state and recommending the preparation of a statewide Climate Adaptation Strategy

- However, no official adaptation plan has been adopted (as of August 2018).

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/michigan/overview.html)