## Impacts

- Minnesota's climate is changing. 

- The state has warmed one to three degrees (F) in the last century. 

- Floods are becoming more frequent, and ice cover on lakes is forming later and melting sooner. In the coming decades, these trends are likely to continue. 

- Rising temperatures may interfere with winter recreation, extend the growing season, change the composition of trees in the North Woods, and increase water pollution problems in lakes and rivers. 

- The state will have more extremely hot days, which may harm public health in urban areas and corn harvests in rural areas.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-mn.pdf)

## State Adaptation / Mitigation Plans

- Since July 2009, Minnesota state agencies have been collaborating on climate adaptation efforts through the Interagency Climate Adaptation Team (ICAT). 

- ICAT includes representatives from a number of Minnesota state departments and agencies, including Agriculture, Commerce, Health, Military Affairs, Natural Resources, Pollution Control, Public Safety, and Transportation, as well as the Board of Water and Soil Resources and the Metropolitan Council. 

- The Minnesota Pollution Control Agency (MPCA) coordinates ICAT, and MPCA has an internal Climate Adaptation Team working on climate resilience strategies for the state as well.

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/minnesota/overview.html)