## Impacts

- In the coming decades, Mississippi will become warmer, and both floods and droughts may be more severe. 

- Unlike most of the nation, Mississippi did not become warmer during the last 50 to 100 years. 

- But soils have become drier, annual rainfall has increased, more rain arrives in heavy downpours, and sea level is rising about one inch every seven years. 

- The changing climate is likely to increase damages from tropical storms, reduce crop yields, harm livestock, increase the number of unpleasantly hot days, and increase the risk of heat stroke and other heat-related illnesses. 
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-ms.pdf)

## State Adaptation / Mitigation Plans

- Mississippi has not developed a statewide adaptation plan. 

- Other resources from the Adaptation Clearinghouse, which have been developed by the state and localities to help communities prepare for climate change, such as: 

- City of Waveland, Mississippi Local Hazard Mitigation Plan	March 2013

- Waveland, Mississippi Local Hazard Mitigation Plan Update – Critical Evacuation Routes	March 2013

- City of Biloxi, Mississippi's 2009 Comprehensive Plan	December 2009

- Long Beach, Mississippi Concept Plan – Oak Park	August 2006

- Design Guidelines and Funding for Elevating Historic Homes in the Mississippi Gulf Coast Region	

- Assessment of Sea Level Rise in Coastal Mississippi	Assessments	July 2011

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/mississippi/overview.html)