## Impacts

- Montana's climate is changing. 

- In the past century, most of the state has warmed about two degrees (F). 

- Heat waves are becoming more common, and snow is melting earlier in spring. 

- Rising temperatures and recent droughts have killed many trees by drying out soils, increasing the risk of forest fires, or enabling outbreaks of forest insects. 

- In the coming decades, the changing climate is likely to decrease the availability of water in Montana, affect agricultural yields, and further increase the risk of wildfires.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-mt.pdf)

## State Adaptation / Mitigation Plans

- In 2019, Governor Steve Bullock issued Executive Order 8-2019, which established the Montana Climate Solutions Council (Council) and joined Montana to the U.S. Climate Alliance. 

- The Executive Order directed the Council to develop the Montana Climate Solutions Plan. 

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/montana/overview.html)