## Impacts

- Nebraska's climate is changing. 

- In the past century, most of the state has warmed by at least one degree (F). 

- The soil is becoming drier, and rainstorms are becoming more intense. 

- In the coming decades, flooding is likely to increase, yet summers are likely to become increasingly hot and dry, which would reduce yields of some crops, require farmers to use more water, and amplify some risks to human health.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-ne.pdf)

## State Adaptation / Mitigation Plans

- Nebraska has not developed a statewide adaptation plan. 

- Other resources from the Adaptation Clearinghouse, which have been developed by the state and localities to help communities prepare for climate change, are highlighted below. 

Nebraska LB 583 - Provide duties for the Climate Assessment Response Committee	Law and Governance	June 4, 2013

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/nebraska/overview.html)