## Impacts

- Nevada's climate is changing. 

- The state has warmed about two degrees (F) in the last century. 

- Throughout the southwestern United States, heat waves are becoming more common, and snow is melting earlier in spring. 

- In the coming decades, the changing climate is likely to decrease the flow of water in the Colorado and other rivers in Nevada, increase the frequency and intensity of wildfires, and decrease the productivity of ranches and farms.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-nv.pdf)

## State Adaptation / Mitigation Plans

- Nevada has not developed a statewide adaptation plan. Other resources from the Adaptation Clearinghouse, which have been developed by the state and localities to help communities prepare for climate change, are highlighted below. 

- Nevada Wildlife Action Plan	Biodiversity and ecosystems, Fish and fisheries, Land management and conservation, Wildlife	March 1, 2013

- All-In Clark County: Clark County's Sustainability and Climate Action Plan	February 16, 2021

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/nevada/overview.html)