## Impacts

- New Jersey's climate is changing. 

- The state has warmed by about three degrees (F) in the last century, heavy rainstorms are more frequent, and the sea is rising about one inch every six years. 

- Higher water levels are eroding beaches, submerging low lands, exacerbating coastal flooding, and increasing the salinity of estuaries and aquifers. 

- In the coming decades, changing the climate is likely to increase coastal and inland flooding, harm coastal and inland ecosystems, disrupt fishing and farming, and increase some risks to human health
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-nj.pdf)

## State Adaptation / Mitigation Plans

- In 2009, during the administration of Governor Jon Corzine, the New Jersey Department of Environmental Protection (NJDEP) recommended that the state develop a statewide adaptation plan in a report titled, Meeting New Jersey's 2020 Greenhouse Gas Limit: New Jersey's Global Warming Response Act Recommendations Report. 

- However, no formal plan was developed at that time and the Office of Climate Change and Energy within NJDEP was closed during the administration of Governor Chris Christie.

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/new-jersey/overview.html)