## Impacts

- New Hampshire's climate is changing. 

- Most of the state has warmed two to three degrees (F) in the last century. 

- Throughout the northeastern United States, spring is arriving earlier and bringing more precipitation, heavy rainstorms are more frequent, and summers are hotter and drier. 

- Sea level is rising, and severe storms cause floods that damage property and infrastructure. 
- In the coming decades, the changing climate is likely to increase flooding, harm ecosystems and winter recreation, disrupt farming, and increase some risks to human health.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-nh.pdf)

## State Adaptation / Mitigation Plans

- In December 2007, Governor John Lynch established a Climate Change Policy Task Force and directed the Task Force to develop a Climate Action Plan (Executive Order 2007-3). 

- The Task Force was composed of 29 members including regulators, scientists, business leaders, utility representatives, and environmental groups; it included a work group focused on adaptation. 

- On March 25, 2009, the Task Force released the New Hampshire Climate Action Plan, which includes a chapter on Adapting to a Changing Climate (Chapter 3) and called for the state to create a stand-alone climate change adaptation plan. 

- As recommended in the plan, the state subsequently established the New Hampshire Energy and Climate Collaborative to facilitate the implementation of the plan's recommendations by bringing together leaders from all sectors of society — government, business, nonprofits, and academia.

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/new-hampshire/overview.html)