## Impacts

- New York's climate is changing. 

- Most of the state has warmed one to three degrees (F) in the last century, heavy rainstorms are more frequent, and the sea is rising about one inch every decade. 

- Higher water levels are eroding beaches, submerging low lands, and exacerbating coastal flooding. 

- In the coming decades, changing the climate is likely to increase coastal and inland flooding, disrupt farming and winter recreation, and increase some risks to human health.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-ny.pdf)

## State Adaptation / Mitigation Plans

- In August 2009, Governor David Paterson established the New York State Climate Action Council (NYSCAC) and directed NYSCAC to create a climate action plan (Executive Order 24). 

- In November 2010, NYSCAC released a 428-page Interim Report ("2010 Report") including measures both to reduce emissions and to prepare for the impacts of climate change. The Interim Report was released for public comment.

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/new-york/overview.html)