## Impacts

- New Mexico’s climate is changing. 

- Most of the state has warmed at least one degree (F) in the last century. 

- Throughout the southwestern United States, heat waves are becoming more common, and snow is melting earlier in spring. 

- In the coming decades, our changing climate is likely to decrease the flow of water in the Colorado, Rio Grande, and other rivers; threaten the health of livestock; increase the frequency and intensity of wildfires; and convert some rangelands to desert. 
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-nm.pdf)

## State Adaptation / Mitigation Plans

- New Mexico has not developed a statewide adaptation plan. 

- Other resources from the Adaptation Clearinghouse, which have been developed by the state and localities to help communities prepare for climate change, such as:

- New Mexico Climate Risk Map	Data and tools	June 17, 2021

- A Climate Change Vulnerability Assessment for Biodiversity in New Mexico	Assessments	December 4, 2008

- The Impact of Climate Change on New Mexico's Water Supply and Ability to Manage Water Resources	Planning	July 2006

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/new-mexico/overview.html)