## Impacts

- North Dakota's climate is changing. 

- In the past century, most of the state has warmed about two degrees (F). 

- Rainstorms are becoming more intense, and annual rainfall is increasing. In the coming decades, longer growing seasons are likely to create opportunities for farmers, and increasing rainfall may benefit some farms but increase the risk of flooding.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-nd.pdf)

## State Adaptation / Mitigation Plans

- North Dakota has not developed a statewide adaptation plan. Other resources from the Adaptation Clearinghouse, which have been developed by the state and localities to help communities prepare for climate change, such as: 

Minot, North Dakota Floodplain Buyouts and Affordable, Resilient Housing ```Buy-In'' Program	Solutions	January 2016

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/north-dakota/overview.html)