## Impacts

- North Carolina's climate is changing. 

- Most of the state has warmed one-half to one degree (F) in the last century, and the sea is rising about one inch every decade. 

- Higher water levels are eroding beaches, submerging low lands, exacerbating coastal flooding, and increasing the salinity of estuaries and aquifers. The southeastern United States has warmed less than most of the nation. 

- But in the coming decades, the region's changing climate is likely to reduce crop yields, harm livestock, increase the number of unpleasantly hot days, and increase the risk of heat stroke and other heat-related illnesses.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-nc.pdf)

## State Adaptation / Mitigation Plans

- In 2002, North Carolina passed the Clean Smokestacks Act (Session Law 2002-4), which directed the Division of Air Quality within the Department of Environment and Natural Resources (DENR) (today the North Carolina Department of Environmental Quality) to study issues related to carbon dioxide emissions. 

- In 2005, the Climate Action Plan Advisory Group (CAPAG) was established to primarily focus on how the state could reduce its greenhouse gas emissions. 

- In 2008, CAPAG released a report with 56 recommendations that could be further researched and considered by the state in the future. Notably, one of the report’s recommendations, CC5, called for a state climate adaptation plan; the state, however, did not pursue a state climate adaptation plan at that point.

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/north-carolina/overview.html)