## Impacts

- Ohio’s climate is changing. 

- Most of the state has warmed by about one degree (F) in the last century. 

- Floods are becoming more frequent, and ice cover on the Great Lakes is forming later or melting sooner. 

- In the coming decades, the state will have more extremely hot days, which may harm public health in urban areas and corn harvests in rural areas.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-oh.pdf)

## State Adaptation / Mitigation Plans

- Ohio has not developed a statewide adaptation plan. 

- Other resources from the Adaptation Clearinghouse, which have been developed by the state and localities to help communities prepare for climate change, such as:

- Columbus, Ohio Climate Adaptation Plan	December 18, 2018

- Cleveland, Ohio Climate Action Plan - 2018 Update	September 21, 2018

- 2018 Green Cincinnati Plan, Ohio: Leveraging Resilience to Become a Climate Haven	April 2018

- Green Cincinnati Plan	April 2018

- Sustainable Cleveland 2019	2018

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/ohio/overview.html)