## Impacts

- In the coming decades, Oklahoma will become warmer, and both floods and droughts may be more severe. 

- Most of Oklahoma did not become warmer during the last 50 to 100 years. 

- But soils have become drier, annual rainfall has increased, and more rain arrives in heavy downpours. 

- In the coming decades, summers are likely to be increasingly hot and dry, which would reduce the productivity of farms and ranches, change parts of the landscape, and possibly harm human health.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-ok.pdf)

## State Adaptation / Mitigation Plans

- Oklahoma has not developed a statewide adaptation plan. 

- Other resources from the Adaptation Clearinghouse, which have been developed by the state and localities to help communities prepare for climate change, such as: 

- Adaptokc: Adapting for a Healthy Future - Oklahoma City, Oklahoma	July 2020

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/oklahoma/overview.html)