## Impacts

- Oregon's climate is changing. 

- Over the past century, most of the state has warmed about two degrees (F). 

- Snowpack is melting earlier in the year, and the flow of meltwater into streams during summer is declining. 

- In the coming decades, coastal waters will become more acidic, streams will be warmer, wildfires may be more common, and some rangelands may convert to desert.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-or.pdf)

## State Adaptation / Mitigation Plans

- Beginning with a 2006, Governor's Climate Change Integration Group (CCIG), with representation from industry leaders, nonprofit organizations, and representatives from federal, state, and local government, Oregon continues to plan for climate change.

- On January 19, 2021, the state released a new version of the Oregon Climate Change Adaptation Framework to provide an updated guide to ensuring Oregon's people, ecosystems, and economy are able to adapt to the impacts of a changing climate. 

- The 2021 Framework is divided into five sections: Why We Must Adapt; Implementing Comprehensive Climate Change Adaptation; Climate Change Effects and Strategic Responses by Theme; Next Steps; and the Oregon Climate Equity Blueprint. 

- The 2021 Framework was developed by a Working Group, composed of 24 state agencies, and coordinated by the Department of Land Conservation and Development.

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/oregon/overview.html)