## Impacts

- Pennsylvania's climate is changing. 

- The commonwealth has warmed more than half a degree (F) in the last century, heavy rainstorms are more frequent, and the tidal portion of the Delaware River is rising about one inch every eight years. 

- In the coming decades, changing the climate is likely to increase flooding, harm ecosystems, disrupt farming, and increase some risks to human health. 
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-pa.pdf)

## State Adaptation / Mitigation Plans

- Adaptation planning in Pennsylvania was driven by the enactment of the Pennsylvania Climate Change Act of 2008, which called for development of a climate impacts assessment and development of a climate change action plan. 

- On January 27, 2011, CCAC released the Pennsylvania Climate Adaptation Planning Report: Risks and Practical Recommendations. 

- The 2011 Plan includes goals identified by each of the workgroups (i.e., infrastructure, public health and safety, natural resources, and tourism and outdoor recreation) to minimize the impacts of climate change on Pennsylvania. Each workgroup considered impacts in multiple areas and sub-sectors. 

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/pennsylvania/overview.html)