## Impacts

- Rhode Island's climate is changing. 

- The state has warmed about three degrees (F) since the year 1900. 

- Throughout the northeastern United States, spring is arriving earlier and bringing more precipitation, heavy rainstorms are more frequent, and summers are hotter and drier. 

- Sea level is rising, and severe storms increasingly cause floods that damage property and infrastructure. 

- In the coming decades, the changing climate is likely to increase flooding, harm ecosystems, disrupt fishing, and increase some risks to human health.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-ri.pdf)

## State Adaptation / Mitigation Plans

- In 2010, the Rhode Island legislature established the Rhode Island Climate Change Commission (RICCC) by passing The Rhode Island Climate Risk Reduction Act of 2010. 

- On September 15, 2017, Rhode Island Governor Gina Raimondo signed Executive Order 17-10, which created the position of state Chief Resilience Officer.

- On April 10, 2021, Governor Raimondo signed the Rhode Island 2021 Act on Climate into law, amending the Resilient Rhode Island Act of 2014 by making mandatory greenhouse gas (GHG) emissions targets more enforceable, adding a goal of net-zero by 2050, and requiring actions to promote equity and environmental justice.

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/rhode-island/overview.html)