## Impacts

- Contrary to this stations' record, most of Texas has warmed between one-half and one degree (F) in the
past century. 

- In the eastern two-thirds of the state, average annual rainfall is increasing, yet the soil
is becoming drier. 

- Rainstorms are becoming more intense, and floods are becoming more severe. 

- Along much of the coast, the sea is rising almost two inches per decade. 

- In the coming decades, storms are likely to become more severe, deserts may expand, and
summers are likely to become increasingly hot and dry, creating problems for agriculture and possibly human
health. 

[EPA Snapshot 2016](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-ws.pdf)

## State Adaptation / Mitigation Plans

- Texas has not adopted an official statewide adaptation plan, however, the state has undertaken other efforts to assess climate vulnerabilities and identify adaptation strategies

- Texas 2017 Coastal Resiliency Master Plan
- Plus dozens of local or regional plans.

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/texas/overview.html)