## Impacts

- South Carolina's climate is changing. 

- Most of the state has warmed by one-half to one degree (F) in the last century, and the sea is rising about one to one-and-a-half inches every decade. 

- Higher water levels are eroding beaches, submerging low lands, and exacerbating coastal flooding. Like other southeastern states, South Carolina has warmed less than most of the nation. 

- But in the coming decades, the region's changing climate is likely to reduce crop yields, harm livestock, increase the number of unpleasantly hot days, and increase the risk of heat stroke and other heat-related illnesses.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-sc.pdf)

## State Adaptation / Mitigation Plans

- South Carolina has not developed a statewide adaptation plan. Other resources from the Adaptation Clearinghouse, which have been developed by the state and localities to help communities prepare for climate change such as:  

- South Carolina Disaster Relief and Resilience Act	Law and Governance	September 29, 2020

- South Carolina Hazard Mitigation Plan - 2018 Update	Coastal, Land use and built environment, Tourism and recreation	October 2018

- City of Charleston, South Carolina Comprehensive Plan 2021	October 12, 2021

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/south-carolina/overview.html)