## Impacts

- Tennessee's climate is changing. 

- Although the average temperature did not change much during the 20th century, the state has warmed in the last 20 years. 

- Average annual rainfall is increasing, and a rising percentage of that rain is falling on the four wettest days of the year. 

- In the coming decades, the changing climate is likely to reduce crop yields, threaten some aquatic ecosystems, and increase some risks to human health. 

- Floods may be more frequent, and droughts may be longer, which would increase the difficulty of meeting the competing demands for water in the Tennessee and Cumberland rivers.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-tn.pdf)

## State Adaptation / Mitigation Plans

- Tennessee has not developed a statewide adaptation plan. Other resources from the Adaptation Clearinghouse, which have been developed by the state and localities to help communities prepare for climate change, are highlighted below.

- Memphis, Tennessee Mid-South Regional GreenPrint	February 5, 2015


- Climate Change and Potential Impacts to Wildlife in Tennessee	Planning	2009

- Economic Impacts of Climate Change on Tennessee	Assessments	September 2008

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/tennessee/overview.html)