## Impacts

- Utah's climate is changing. 

- The state has warmed about two degrees (F) in the last century. 

- Throughout the western United States, heat waves are becoming more common, and snow is melting earlier in spring. 

- In the coming decades, the changing climate is likely to decrease the flow of water in Utah’s rivers, increase the frequency and intensity of wildfires, and decrease the productivity of ranches and farms. 
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-ut.pdf)

## State Adaptation / Mitigation Plans

- Utah has not developed a statewide adaptation plan. 

- Other resources from the Adaptation Clearinghouse, which have been developed by the state and localities to help communities prepare for climate change, such as:

- Sustainable Salt Lake - Plan 2015 (Salt Lake City, Utah)	March 18, 2013


- Climate Change and Public Health in Utah	Assessments	2012

- Climate Change in Park City, Utah: An Assessment of Climate, Snowpack, and Economic Impacts	Assessments	September 29, 2009

[Source: Georgetown Climate Center](https://www.georgetownclimate.org/adaptation/state-information/utah/overview.html)