## Impacts

- Vermont's climate is changing. 

- The state has warmed by more than two degrees (F) in the last century. 

- Throughout the northeastern United States, spring is arriving earlier and bringing more precipitation, heavy rainstorms are more frequent, and summers are hotter and drier. 

- Severe storms increasingly cause f loods that damage property and infrastructure. 

- In the coming decades, changing climate is likely to harm ecosystems, disrupt agriculture and winter recreation, and increase some risks to human health. 
    
[Source: EPA Snapshot (2107)](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-vt.pdf)

## State Adaptation / Mitigation Plans

- Vermont has not adopted an official statewide adaptation plan, however, the state has undertaken other efforts to assess climate vulnerabilities and identify adaptation strategies.

- In 2011 and again in 2012, then Governor Peter Shumlin established Vermont's Climate Cabinet, and called on state agencies to take specific steps to reduce greenhouse gas emissions and prepare for the impacts of climate change (Executive Order 15-12)

- In July 2017, Governor Philip Scott issued an executive order creating a Climate Commission and tasked the Commission to develop a set of recommended actions the state can take to meet its renewable energy and greenhouse gas reduction goals “while driving economic growth, setting Vermonters on a path to affordability and ensuring effective energy transition options exist for all.”

- In September 2020, the Vermont State Legislature passed the Vermont Global Warming Solutions Act (H.688), which requires the state to pursue climate solutions that reduce greenhouse gas (GHG) emissions and support environmental and economic resilience. 

[Source: Georgetown Climate Center (Research last updated: January 7, 2021)](https://www.georgetownclimate.org/adaptation/state-information/vermont/overview.html)