## Impacts

- Virginia's climate is changing. 

- Most of the state has warmed about one degree (F) in the last century, and the sea is rising one to two inches every decade. 

- Higher water levels are eroding beaches, submerging low lands, exacerbating coastal flooding, and increasing the salinity of estuaries and aquifers. 

- The southeastern United States has warmed less than most of the nation.

- But in the coming decades, the region's changing climate is likely to reduce crop yields, harm livestock, increase the number of unpleasantly hot days, and increase the risk of heat stroke and other heat-related illnesses. 

[EPA Snapshot 2016](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-va.pdf)

## State Adaptation / Mitigation Plans

- Adapt Virginia ("AdaptVA") is a web portal designed to provide climate information, data, and tools tailored for Virginia users, including local governments, emergency managers, state agencies, and home and business owners, among others. 

- The portal includes data, tools, case studies, example plans, laws and policies to help Virginia decisionmakers adapt to rising seas and other impacts of climate change. 

[Source: Georgetown Climate Center](https://www.georgetownclimate.org/adaptation/state-information/virginia/overview.html)