## Impacts

- Washington's climate is changing. 

- Over the past century, most of the state has warmed one to two degrees (F). 

- Glaciers are retreating, the snowpack is melting earlier in the year, and the flow of meltwater into streams during summer is declining. 

- In the coming decades, coastal waters will become more acidic, streams will be warmer, populations of several fish species will decline, and wildfires may be more common.
    
[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-wa.pdf)

## State Adaptation / Mitigation Plans

- In 2009, the Washington State Legislature required state agencies to reduce emissions and develop an integrated climate change response strategy (through the State Agency Climate Leadership Act).

- In 2016, to build momentum around statewide adaptation work, Washington agencies created the Washington Interagency Climate Adaptation Network (ICAN). 

- In May 2019, Governor Jay Inslee signed into law Substitute Senate Bill (SSB) 5106, which mandates the establishment of a Natural Disaster and Resiliency Activities Work Group.

[Source: Georgetown Climate Center (Research last updated: July 28, 2020)] (https://www.georgetownclimate.org/adaptation/state-information/washington/overview.html)