## Impacts

- Wyoming’s climate is changing. 
- In the past century, many parts of `r files$state` has warmed by one to three degrees (F)
- Heat waves are becoming more common, and snow is melting earlier in spring. 
- Rising temperatures and recent droughts have killed many trees by drying out soils, increasing the risk
of forest fires, or enabling outbreaks of forest insects. 
- In the coming decades, the changing climate is likely to decrease the availability of water in Wyoming, affect agricultural yields, and further increase the risk of wildfires. 
    
[Source: EPA Snapshot (2107)](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-wy.pdf)

## State Adaptation / Mitigation Plans

- Wyoming has not developed a statewide adaptation plan.
- A wide range of organizations have developed ``resources'' to promote good land, water use, to a wide range of stakeholders, e.g. NGOs, Tribes, and Federal Agencies ([Adaptation Clearing House](https://www.adaptationclearinghouse.org/search/?sid%5B%5D=313)).

[Source: Georgetown Climate Center](https://www.georgetownclimate.org/adaptation/state-information/wyoming/overview.html)