---
title: "Untitled"
author: "Mason Asoto"
date: "10/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Blog Draft

Within our group we had many interests from, health impacts to socio economic factors affecting communities and how fire policy has impacted certain communities. After combining all of our interest, we came up with a group question of, “After a forest fire, is there a difference in the number of cardiovascular and pulmonary hospital admissions among the elderly in primarily white and non-white neighborhoods?” Our null hypothesis is that there is no statistical difference in hospital admissions between residents of geographically proximate white and non-white neighborhoods. I chose to analyze socio economic factors that helps explain the difference in hospital admissions between the two communities. Also, I am looking at social identities at the neighborhood level and how they compare to overarching trends. 

The fire that we are analyzing data from is the Witch Fire which happened in the San Diego County from October 21st, 2007 through November 13th, 2007. The Witch Fire also known as the Witch Creek Fire and the Witch–Guejito–Poomacha Complex Fire, was the second- 
largest wildfire of the 2007 California wildfire season. The Witch Fire burned 197,990 acres (801 km2) alone, however, it merged with the Poomacha and McCoy Fires, where it was then called the Witch–Guejito–Poomacha Complex Fire that had a total burn area of 247,800 acres (1,003 km2). The Witch–Poomacha Fire caused at least $1.3 billion (2007 USD) in insured damages alone, becoming the costliest wildfire of 2007. As of 2018, the Witch Fire is the ninth-largest wildfire in modern California history, as well as the fifth-most destructive wildfire on record in California. 

There are two hospital admission data that we are analyzing, the first hospital is Tri-City Medical Care and the second is Scripps Mercy Hospital. When comparing Tri-City Medical Care hospital data admission to socio economic factors, I looked at the 92056 zip code of San Diego County which includes the cities of: Oceanside, Carlsbad and Vista. There is an estimated population of 54,693 residents in this zip code. The land area is 12.4 sq. miles and there is an average of 4,407 people per square mile. The Average Adjusted Gross Income (AGI) for the 92056 zip code in 2012 was $56,926. The Average Adjusted Gross Income for the state of California was $72,726. In the graphs to the right it shows the distribution of Residents’ Ages in the 92056 county. The median resident age is 40.4 years old. When looking at the racial statistics of the community, about 53% of the population is White, 28% is Hispanic or Latino, 5% is Asian and 14% is other. 
	
	

The second hospital admission data that we analyzed is the Scripps Mercy Hospital. The Scripps Mercy Hospital is part of the 92103 zip code which includes the city of San Diego. The estimated zip code population in 2016 was 34,358 residents. The land area: 3.8 sq. miles with a population density of 9,123 people per square mile. Average Adjusted Gross Income (AGI) for the 91203 zip code in 2012 was $84,695. The graphs to the right it shows that the median age is 39.5 years old. Racial statistics include: 67% of the population is White, 13% of the population is Hispanic or Latino and 5% of the population is Asian. 

The Tri-City Medical Care community is below the state average when referring to income levels and compared to the Scripps Mercy Hospital community, there is a greater racial diversity in the population. In the Scripps Mercy Hospital community, the income levels are above state average where it is a predominantly White community. Prior to analyzing the data and comparing it to socio economic factors, I thought about reasons why there might be a greater hospital admission in the Tri-City Medical Care community vs. the Scripps Mercy Hospital or vis versa. I thought about low income factors such as, housing crowdedness, completion of education, parental presence that are correlated to fire risks that might be found in the Tri-City Medical Care community because they have a lower income compared to the Scripps Mercy Hospital community. Then when thinking about why the Scripps Mercy Hospital community might have a higher hospital admission I took a more psychological approached and thought out about how higher income communities are more cautious about their health, where as a lower income community may not be able to go to the hospital even if they are sick, because they are not able to afford it or not able to miss work or leave their children alone. 

	The first data that I am going to analyze is the racial statistics of the Tri-City Medical Care hospital admission data from October 15th, 2007 through November 20th, 2007. When looking at the graph there was a spike on October 22nd, 2007, which was the second day after the fire first started. However, after that spike there was a pretty constant hospital admission. The average hospital admission throughout this time period was 180.97 patients. When it came to age statistics, there was pretty consistent data throughout the time period for all ages except there were three days from October 27th through October 29th where hospital data for ages 0 through 18 spiked. 

	When analyzing the racial statistics of the Scripps Mercy Hospital admission data from October 15th, 2007 through November 20th, 2007, there was a similar spike of hospital admission data the second and third day of the fire, October 22nd and October 23rd, 2007. However, after that there was a mild decrease in hospital admission data. This trend was similar with the age statistics where it was a pretty consistent trend with a mild decrease of hospital admission. 

	There could be many explanations of these trends such as there could have been burn victims due to not evacuating in time and that’s why during the first few days of the fire there was a spike in hospital admissions. A possible explanation for why there was a spike in hospital admission for ages 0 through 18 for the Tri-City Medical Care admission data is that since the evacuation process was still in the early process, people were breathing in smoke and parents admitted their children to the hospital to make sure they were okay. One possible explanation of why the trend decreased was because people were evacuating so they may have left the San Diego County area.

	In conclusion, this data set did not show any overall trends of hospital admission for the Tri-City Medical Care Hospital and the Scripps Mercy Hospital when it came to race and age. There are many variables and explanations that would require more research such as finding out what amount of the population evacuated, the wind patterns of the San Diego County and if the smoke was blown into the cities or into the mountains, and more that would help explain the overall trends of hospital admissions. 

















## Reference

“92056 Zip Code (Oceanside, CA) Detailed Profile.” Crime in Pine Bluff, Arkansas (AR): Murders, Rapes, 
Robberies, Assaults, Burglaries, Thefts, Auto Thefts, Arson, Law Enforcement Employees, Police Officers, Crime Map, www.city-data.com/zips/92056.html.

“92103 Zip Code (San Diego, CA) Detailed Profile.” Crime in Pine Bluff, Arkansas (AR): Murders, Rapes, 
Robberies, Assaults, Burglaries, Thefts, Auto Thefts, Arson, Law Enforcement Employees, Police 
Officers, Crime Map, www.city-data.com/zips/92103.html.

“Data and Reports Archive.” OSHPD, 19 June 2017, oshpd.ca.gov/data-and-reports/.

“Licensed Healthcare Facility Listing.” California Health and Human Services Open Data Portal, 
data.chhs.ca.gov/dataset/licensed-healthcare-facility-listing.

“North County San Diego Hospital - Family Medicine, Cancer Care.” Tri-City Medical Center, 
www.tricitymed.org/.

“Scripps Mercy Hospital - San Diego, California.” Scripps Health, 3 Apr. 2018, 
www.scripps.org/locations/hospitals/scripps-mercy-hospital.


