---
title: "The Benefits of a Return to a Natural Fire Regime Through Small Fires and Prescribed Burns"
author: "Alexander AJ Dykens-Hodapp"
date: "10/9/2018"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In California the question isn’t if there will be a fire, but when, where and for how long. Large fires like the ones seen in Mendocino, Ventura, and Santa Barbara cast a new light on approaches to fire management. California’s natural fire regiment has been significantly altered through the long term use of practices like containment and suppression of any and all fires. This paper will look at the prevalence of smaller fires across the state, and compare them with the average acres burned in the region. Through allowing smaller fires to burn out, and reduce the amount of fuel sources in these areas, the duration, intensity and destruction of larger fires can potentially be avoided. Restoring to any extent possible, the natural fire regime, will benefit California’s forests and people. 
The average amount of acres burned in a given county was 16,789. In the 2 counties with more than 13 fires the average was instead 419 acres burned (Riverside, San Diego). Additionally, Riverside County had 21 total fires, (the most so far in 2018), with an average of only ~136 acres burned. In contrast Sacramento had an average of 8379 acres burned. Lassen had  8,070 and Modoc County had 17,028 as averages of their acres burned. All three previously mentioned counties had less than 4 fires total. While this data is not conclusive, and only has the first 10 months of 2018, it does seem to represent a trend in which a county has a larger amount of smaller fires, and avoids larger, longer and more destructive fires.
In looking at fuel management, it is important to bring in the data around prescribed burns as a possible model for the outcomes of allowing smaller fires to burn out. The graph shows that an increase in prescribed burns lowers the total acres burned by larger wildfires. There was one outlier of Shasta County, which had 277,884 acres burned due to the Carr fire, much higher than any other fires this study looked at. Here the prevalence of smaller controlled fires has the effect of reducing the overall acres burned in a given county. This idea could be extrapolated to larger fires that are allowed to burn out, covering much more ground than smaller controlled burns. 
	
The policy in California, and more broadly the US, has been suppression and containment of any and all fires. Small fires in moist air conditions with little chance of spreading are put out, only to have a larger, longer fire happen in the same place during the middle of the fire season. Fire ecologists, Jon Keeley states “Despite increased expenditures on fire suppression, each new decade experiences increased loss of property and lives from brushland wildfires” (Keeley 20XX). Although not all ecosystems in California could be considered brushland ecosystems, it does seem indicative that fire suppression doesn’t seem to be effective in reducing fires, even with increased funding.
Allowing small and prescribed fires to burn when applicable in California appears to have a good chance of reducing the duration and intensity of these record breaking fires. Helping to restore the natural fire ecology must be the primary goal of fire and forest management in California. 


Problems we ran into:
	Throughout our research process, we found that the data recorded on each county’s Strategic Wildfire Plan was inconsistent throughout each county. Certain counties had extensive reports about the acreage of fuel treated lands, prescribed fires, as well as acreage of each wildfire reported. Other counties merely had a description of the requirements of fuel management or prescribed fire (ex: laws or permits needed for prescribed burns). We also found that the lack of detail on fuel management sections in the wildfire plans may indicate that the county doesn’t prioritize fuel management compared to suppression. It may also imply that their data collection methods are either nonexistent or disorganized. It could also be possible that data from these counties may be published on websites we couldn’t find. It would be helpful if each county were required to follow a template when filling out their yearly Strategic Wildfire Plans. This would be a good way to hold countries accountable for giving the public accurate and thorough information that can be easily compared to neighboring areas. 


