---
title: "Fire Ecology in Griffith Park"
author: "Virginia Paschal"
date: "10/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## How do historical fires in WUIs shape our contemporary management practices? 

### Introduction 
Griffith Park is one of the most recognizable features of recreation and culture within the city of LA, and it is the largest municipal landmark in the United States. Its 4300+ acres of diverse Californian ecology and modern infrastructure  serve as a space for natural, cultural, and interstellar exploration by both residents of Los Angeles and visitors from around the world. In the past fifty years within Griffith Park there here have been over thirty wildfires, The frequency of fires within this park makes it a fascinating site to study not only because of its immense diversity in native wildlife and vegetation but also because of its multi-use space  as an urban center that hosts hundreds of people every day.  
In a region increasingly defined by severe and unpredictable wildfires within Wildland Urban Interfaces, fire management in Griffith Park can serve as a telling example to Californians of how historical fires and understandings of ecology can successfully shape best management practices. 
Vegetation vs. where  fires occur
The vegetation covering Griffith Park includes mixed chaparral, mixed scrub, oak-sycamore riparian, oak woodland, and walnut woodland (all natives) and some areas of non-native vegetation including pine and eucalyptus plantations. (FOG, 3.3) This vegetation is characterized by its flammability and hardiness to drought. 
The deadliest wildfire in California occurred in Griffith Park in late 1933. Thought to be caused by a carelessly discarded cigarette butt, the fire eventually enveloped over 47 acres. While by today’s standards this would be defined as a relatively harmless and easily controllable burn, the people charged with fighting the fire were largely laymen with no training in fire suppression and as a result, 29 people were killed. Two large fires have since followed.  A fire in 1961 burned 841 acres and a fire in 2007 burned 817 acres, both of these occurred in the southern most quadrants of the park (FOG, 7.2).

## Recovery and Prevention 
Multiple recovery and prevention methods have been experimented with following these major fire outbreaks.. A major area of discussion within Friends of Griffith Park ( a community organization centered around the continued ecological health of Griffith Park) and various other members of the community concerning the best way to address the frequency of wildfires within Griffith park.  More ecological centered community members believe the fires are simply a consequence of human interaction with the wilderness in the park and are simply a fact that must be accepted as opposed to attempting to prevent.  
Analysis/ What we need to finish
We have built a GIS story map showing the spatial history of fires within Griffith Park and who Is responsible for managing them. There is a specific area on the map with a high concentration of past fires and we wanted to investigate the reasonings behind this by figuring out what the primary vegetation in that area, the foot traffic through this spaces as compared to the rest of the park, and if management practices in this area differed from the rest of the park. However, we ran into trouble finding published fire management practices over any area of the park other than a paper discussing recovery methods after the 2007 fire.  We also ran into trouble finding information about which areas of the park were occupied by specific types of vegetation. We are in the process of working with Guillermo to  widen the scope of our analysis so we have more resources/data to work with. 




Works Cited
Cooper, Daniel, and Paul Mathewson. “Griffith Park Wildfire Management Plan.” Friends of Griffith Park , 2008, www.friendsofgriffithpark.org/gpwildlifemgtpgm.pdf. 

azo Santoyo, Laura. Fire prevention in Los Angeles County: a survey of the methods and strategies used in the wildland-urban interface. Diss. California State Polytechnic University, Pomona, 2015.

Nunamaker, Claralynn. “Wildfire and Fuel Management.” University of California Forest Research and Outreach, 2007, www.anrcatalog.ucanr.edu/pdf/8245.pdf. 

Debats, Stephanie. “Effect of Hydromulch and Fire Intensity on Post-Fire Chaparral: A Griffith Park Case Study.” Research Gate, 2008, www.researchgate.net/publication/228638020_Effect_of_Hydromulch_and_Fire_Intensity_on_Post-Fire_Chaparral_A_Griffith_Park_Case_Study.

