---
title: "The Pines' on Fire: Thinning Practices and Wildfires within Colorado's Ponderosa Pine Forests"
author: "Vanessa"
date: "10/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Ponderosa Pine Forests in Colorado

The Ponderosa Pine is one of several tree species found in Colorado’s rocky, emerald topography,
occupying nearly 3 million acres in the state (Ament and Fishering 2004). While it
can be found scattered across western United States, it is located within Colorado’s southwest
and Front Range foothills (Ament and Fishering 2004). Though mostly in the southwest, Ponderosa
Pine stands—stands being a group of trees of the same species—are the backyard of
several Colorado homes, in fact, 75% of communities identified as being at-risk from wildfires
live within a mile of Ponderosa Pine stands (Ament and Fishering 2004). Ponderosa Pines
not only coexist with human ecosystems, such as physical homes and watersheds, but with
diverse surrounding mountainous and grassland ecologies (Ament and Fishering 2004). Having
to adapt to such varying conditions over the years has made it a very resilient species,
and is even characterized as being “disturbance driven,” a species that evolves along with the
natural cycles of its surrounding ecosystem (Ament and Fishering 2004).

## Thinning Practices

Being disturbance driven and highly adaptive, Ponderosa Pines are resilient to, and even
thrive after, low-intensity wildfires. In fact, research has found that Ponderosa Pine forests
had developed their own cycles of low-intensity natural wildfires that would thin the forest,
killing off weaker trees and other competing conifer seeds on the ground such as pine needles,
allowing taller and healthier trees to thrive (Ament and Fishering 2004). These sort of natural
wildfires are beneficial and vital to health of Ponderosa Pine forests.
However, being that the Ponderosa Pine forests make up a significant chunk of Colorado’s
wildland-urban interface, it has been subject to several artificial forms of thinning and like
fire-suppression techniques. The most common forms of thinning are “thinning from below,”
the practice of removing only small and mid-sized trees which keeps the canopy and trunks
of larger trees from being fuel for wildfire, and “prescribed fires,” which are small controlled
wildfires that mimic Ponderosa Pines’ natural wildfires cycles that burn off wood debris and
seeds that could be fuel for larger wildfires (Ament and Fishering 2004). Such precautions
are taken to mitigate the risk of high-intensity wildfires within Ponderosa Pine forests and
therefore mitigate the negative impact wildfires can have on surrounding infrastructure and
families. But how successful have they been?

## It’s Complicated: The 2002 Hayman Wildfire

The Hayman Wildfire, one of Colorado’s largest and most destructive wildfires, took place
in June of 2002 around the Front Range of the Rocky Mountains, severely impacting the
Ponderosa Pine forest ecosystem there, consuming around 47,000 acres at a fast rate (Graham
and Jain 2005). A few days prior to the fire, several thinning techniques, such as thinning from
below and other fuel treatments (totaling to 13,312 acres) and prescribed wildfires (totaling to
6,358), were performed on several parts of the Front Range in anticipation of a high-intensity
wildfire (Martison, Omi, Shepperd). Interestingly enough, such thinning and fire suppression
techniques both mitigated the impact of the wildfire on some parts of the Front Rage and also
had no impact on other parts, it was very inconsistent (Martison, Omi, Shepperd). It was
clear though that fuel treatments were most effective, as the wildfire had less of an impact of
on the landscape that had fuel treatment days prior than the landscape that had not, Figure
2 (Graham and Jain 2005). Even then, clearing of fuel had little impact during the peak days
of the fire (Martison, Omi, Shepperd). Thus demonstrating that the effectiveness of thinning
techniques is complex but can nonetheless have positive results.

## Concluding Remarks
Although the risk of wildfires is a, no pun intended, hot topic for Colorado’s Ponderosa Pine
forests given their strong presence in the wildland-urban interface, there is no simple solution
to tackling the issue. While thinning techniques have demonstrated effectiveness, it is not a
perfect nor reliable solution, as evidenced by the case of the Hayman wildfire. The Colorado
government has several challenges ahead of it, especially given the increase in fuel presence
in Ponderosa Pines with the Colorado mountain pine beetle increasingly killing Ponderosa
Pines and consequently leaving large numbers of dead trees and debris in forests that are just
waiting to aggravate a wildfire, among other challenges (Report on the Health of Colorado’s
Forests 2016). As wildfires grow and challenges surrounding them become more complex, our
solutions and approaches should grow and morph along with them.


## References

Ament, Don, and Nancy Fishering. 2004. “Colorado Forestry Advisory Board Members:,” 36.
Colorado State Forest Service. “REPORT ON THE HEALTH OF COLORADO’S FORESTS:
FIRE AND WATER.” January 2017. Accessed October 2018. https://csfs.colostate.edu/
media/sites/22/2017/02/CSU_304464_ForestReport-2016-www.pdf .
Graham, Russell T, and Theresa B Jain. n.d. “Ponderosa Pine Ecosystems,” 32.
Martinson, Erik, Phillip N. Omi, and Wayne Shepperd. “Part 3: Effects of Fuel Treatments
on Fire Severity.” USDA Forest Service. 2003. Accessed October 2018. https://www.fs.fed.
us/rm/pubs/rmrs_gtr114/rmrs_gtr114_096_126.pdf .
