---
title: "Fire Suppression in Southwest Australia"
author: "Catherine Ward"
date: "10/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Fire Ecology in Southwest Australia
The Southwest tip of Australia is a biodiversity hotspot, which is classified as a place with an exceptional concentration of endemic species undergoing rapid loss of habitat. It was one of the original 25 locations singled out worldwide in 2000, and the only hotspot in Australia. The Southwest tip is known to indigenous Australis as Kwongan, and is home to an array of 7,329 vascular plant species, 80% of which are found nowhere else in the world. This location has remained largely undisturbed by geologic and anthropogenic influences for millions of years. This has allowed and exceptionally rich and stable biosystem to flourish, and it is an international concern to protect this location from exceptional habitat loss.

This location is sometimes referred to as the Southwest Australian Floristic Region (SWAFR) in scientific circles. SWAFR is described as a mediterranean climate with hot dry summers, and cool wet winters. The soil comes from a flat granite plateau and is nutrient deficient, because there has been no glacial or geologic activity in the region for millions of years. The primary flora in the region are low closed Eucalyptus forest, acacia woodlands, and tall closed shrublands. The taxa of the region is fire adapted and weathers cyclical wildfires. Unfortunately this area is under severe habitat stress due to encroaching human development coming down the coastline.

Human development in the region has created WUI’s in sensitive biologic areas. WUI’s bring with them an increased risk of fire, but they also bring invasive plant and animal species that could spread to habitats vulnerable from fire exposure. Local and international concerns have been raised about protecting this sensitive place and furthering regulating development on the fringes of the region.


## Thinning in Southwest Australia Floristic Region

Australia has an interesting history with fire management. Australia has a dry climate, and fire is part of the natural cycle of local wildlife. The indigenous people of Australia have practiced thinning and controlled burns for millennia, but this practice was largely ignored and abandoned by Australian colonizers. In the 1950’s officials recognized the need for controlled burns, and combined indigenous knowledge with modern technology to build national prescribed burning programs. The Department of Energy and Conservation. “Each year the DEC aims to conduct prescribed burns over 6 % to 8 % of the 2.5 million hectares of forested lands within the DEC-managed estate,”.

Prescribed burning in the SWAFR is an important tool for protecting the ecosystem from uncontrolled fire threats and invasive species. Protecting the region comes with challenges though. The Eucalyptus heavy mediterranean climate is exclusive to the region so state fire policies can’t be applied. Fires in the region can be hard to predict, some wildfires are surface fires, and some are blazing crown fires that can envelope a whole forest. This region has a high rate of WUI’s, with almost half a million people living in sensitive areas. The DEC manages the region in a two pronged approach. They constantly monitor the region using a fire detection system backed up by stationed fire fighting forces. They also employ a rotational prescribed burning program to ensure there is never an excessive buildup of fuel. They burn approximately 100,000 hectares a year, which accounts for 82% of all ha burned in the region planned or unplanned.

This program has shown to be largely effective. There have only been two major fires in the last 50 years, one in the Jarrah region near Perth in 1961, and one in the Karrah forest in 1969. To put in perspective, regions that once had wildfires every 4.5 years now have a prescribed burn every 9 years. It has been shown in the region that low thinning is far more effective for fire prevention and ecosystem health than crown thinning. There is some concern over whether thinning is reducing critical habitats, and contributing to species loss. However, a study was done that varied the time intervals between prescribed burns and there was very little difference in the abundance or richness of species composition.


## Analysis of Fire Prone Flora in SW Australia

Analysis of Fire Heat in SW Australia since 2000
Using the NASA FIRMS database brightness measurement to track fire heat data in SWFAR from 2000 to now.
``` > View(SWFAR_FireData_2000_2018)


Thinning Issues in Southwest Australia

The future of fire management in Australia will become more complicated as the years go on. The government is remiss to stop development in Southwest Australia. It is one of their most quickly growing regions, due in large part to the SWAFR’s proximity to Perth. Australia has very hot summers and the threat of climate change has increased the threat of wildfires in the area. F Most wildfires in Australia occur during ‘blow-up’ conditions, which are high temperatures and hot dry winds. These blow-up periods have become more frequent as the earth has warmed. The SWAFR region is sensitive because it is a nutritionally deficient landscape. Also the entire region is on a low granite plan with few mountains. This means if there were a large wildfire it could spread uncontrollably for thousands of hectares. The DEC thinning program is well regarded in Australia, however environmental advocates worry that thinning might be irreparably hurting endangered species habitat in the region. A common question asked is whether wildfires would be common is there were no thinning in the region. Some believe prescribed burns unnecessarily burden the local fauna in order to protect increasing development interests in the region.


## References

Boer, Matthias M., et al. “Long-term impacts of prescribed burning on regional extent and incidence of wildfires—evidence from 50 years of active fire management in SW Australian forests.” Forest Ecology and Management 259.1 (2009): 132-142.
Ecological Restoration Institute. “Effects Of Forest Thinning Treatments on Fire Behavior.” Ecological Restoration Institute - Northern Arizona University, Northern Arizona University, nau.edu/eri/resources/for-policymakers/effects-of-thinning/.
J.K. Ruprecht, N.J. Schofield, D.S. Crombie, R.A. Vertessy, G.L. Stoneman, Early hydrological response to intense forest thinning in southwestern Australia, Journal of Hydrology, Volume 127, Issues 1–4, 1991, https://doi.org/10.1016/0022-1694(91)90118-2.
Sneeuwjagt, Rick J., Tim S. Kline, and Scott L. Stephens. “Opportunities for improved fire use and management in California: lessons from Western Australia.” Fire Ecology 9.2 (2013).
Underwood, R. J., R. J. Sneeuwjagt, and H. G. Styles. “The contribution of prescribed burning to forest fire control in Western Australia: case studies.” Symposium on Fire Ecology and Management of Western Australian Ecosystems’.(Ed. JR Ford) WA Institute of Technology (WAIT) Environmental Studies Group Report. No. 14. 1985.
Wittkuhn, Roy S., et al. “Variation in fire interval sequences has minimal effects on species richness and composition in fire-prone landscapes of south-west Western Australia.” Forest Ecology and Management 261.6 (2011): 965-978.
https://www.vox.com/2015/9/17/9347361/wildfire-management-prescribed-burnhttps://www.sciencedirect.com/science/article/pii/0022169491901182
install.packages(“XML”)
