---
title: "Fire and Evapotranspiration: Understanding the Correlation between Wildfire Disturbances and Hydrological Cycles in California"
author: "Hans Zhou"
date: "October 8, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

  The increasing number of wildfires in California has caused many losses of human lives and properties. As we pay more attention to the causes and prevention of wildfires, we start to realize the complicity of wildfires not only in terms of their origins but also their effects on different aspects of both natural and urban environments. The study of fire ecology is interdisciplinary: while many scholars are studying the social and political implications of the fires, others focus on the health of the ecosystem impacted and susceptible to fire. 
  
  Recent attention has been paid to the relationship between climate change and fire frequencies, particularly on how the rising temperature contributes to fires in the region. As the state of California has experienced a multi-year drought since 2011, it is also crucial to examine the relationship between wildfire disturbances and hydrological cycles because water plays an important role in determining the susceptibility of an ecosystem to fire and in the post-fire resilience. This blog post aims to provide an overview of the existing studies on fire and hydrological cycles around the world and to analyze the impacts of thinning, as a fire prevention practice, on evapotranspiration in California. 

# Evapotranspiration

  Evapotranspiration, often referred to as ET, is the process of transporting moisture from the earth into the atmosphere. As Figure 1 indicates, evapotranspiration is the combination of the evaporation of water in the ground the transpiration of water from the ground through plants. Evapotranspiration is important because it is a crucial aspect of the hydrological cycle on the earth, and it accounts for about 10-15% of the water in the atmosphere. There are many factors that influence evapotranspiration, including temperature, relative humidity, wind, solar radiation, etc. 
  
  Evapotranspiration is widely used in agriculture to provide guidelines for irrigation systems. It is a good indicator of how much water has entered and left the plants. An ET-based irrigation system helps reduce water cost and increase agricultural productivity. Ecologists also use ET as a measurement to study the health of a forest ecosystem since it is a crucial aspect of the forest’s hydrological cycle. 
  
# Existing Case Studies
Many studies have been conducted in Canada regarding the conditions of evapotranspiration in disturbed forests. A study conducted by Kettridge at al. (2006) indicates that subcanopy evapotranspiration critically determines peatland carbon stock vulnerability to wildfire. In addition, it affects water availability between different landscapes. Bond-Lamberty at al. (2009) concluded that wildfire is a significant driving factor in changes of hydrological processes in the Canadian boreal forest. These changes influence both the growth of the forest and the regional climate. 

# Thinning and Evapotranspiration in California
Comparison between data from Satellite Irrigation Management Support (SIMS) & Fire/Thinning Data in California

# Discussion

# Conclusion & Future Directions

References 
Bond-Lamberty, B., S. D. Peckham, S. T., Gower and B. E. Ewers (2009). Effects of fire on regional 
evapotranspiration in the central Canadian boreal forest. Global Change Biology, Vol. 15, Issue 5, 1057-1363. doi: 10.1111/j.1365-2486.2008.01776.x

Kang, K., J. S.Kimball, and S. W.Running (2006). Simulating effects of fire disturbance and climate change on boreal forest productivity and evapotranspiration. Science of The Total Environment, 362, 85-102. https://doi.org/10.1016/j.scitotenv.2005.11.014

Kettridge, N.,  M. C. Lukenbach, K. J. Hokanson,  C. Hopkinson, K. J. Devito, R. M. Petrone, C. A. 
Mendoza, and J. M. Waddington (2017). Low evapotranspiration enhances the resilience of peatland carbon stocks to fire. Geophysical Research Letters, 44, 9341–9349. https://doi.org/10.1002/ 2017GL074186 

Poon, P. K., and A. M.Kinoshita (2018). Spatial and temporal evapotranspiration trends after 
wildfire in semi-arid landscapes. Journal of Hydrology, 559, 71-83. https://doi.org/10.1016/j.jhydrol.2018.02.023 

Roche, J. W., M. L. Goulden, and R. C. Bales (2018). Estimating evapotranspiration change due to 
forest treatment and fire at the basin scale in the Sierra Nevada, California. Ecohydrology, Vol. 11, Issue 7. https://doi.org/10.1002/eco.1978 






