---
title: "lead"
author: "Caroline Koh Smith"
date: "12/4/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## LEAD ANALYSES

```{r file, echo=FALSE}
##file.choose()
file="/home/CAMPUS/ctsa2016/Climate_Change_Narratives/Student_Folders/Caroline_Koh_Smith/LEAD CAROLINE KOH SMITH/171116_EA30_MLH4_revised.csv"
import=read.csv(file)
head(import)
Pb_data = import[import$Analyte=="Pb",]
head(Pb_data)
Pb_data$Soil_Pb = 25/5*Pb_data$Concentration
drops <- c("Concentration")
Pb_data = Pb_data[ , !(names(Pb_data) %in% drops)]
Pb_data = Pb_data[!Pb_data$Park=="Blank", ]
droplevels(Pb_data$Park)
levels(Pb_data$Park)
library(gdata)
drop.levels(Pb_data$Park)
library(tidyr)
```

```{r iso, echo=FALSE}
Pb = Pb_data %>% spread(Mass, Soil_Pb)
Pb$Pb67 = round(Pb$'206'/Pb$'207',3)
Pb$Pb68 = round(Pb$'206'/Pb$'208',3)
Pb$Total = Pb$'206'+ Pb$'207'+ Pb$'208'
Pb
exceed = sum(Pb$Pb67 > 1.14); exceed
prop.test(exceed, length(Pb$Pb67))
Pb.aov = aov(Total ~ Park, data=Pb)
boxplot(Total ~ Park, data=Pb)
summary(Pb.aov)
boxplot(Pb67 ~ Park, data=Pb)
summary(aov(Pb67 ~ Park, data=Pb))
```

```{r parkz, echo=FALSE}
##CHAPARRAL to 210
Pb$Distance = NA
Pb$Distance[Pb$Park=="C"] <- 0.1
##WHEELER to 10
Pb$Distance[Pb$Park=="W"] <- 0.5
##ROSA TOREZ to 10
Pb$Distance[Pb$Park=="R"] <- 1.5
##GRIFFITH to 210
Pb$Distance[Pb$Park=="G"] <- 0.4
##PUERTA to 210
Pb$Distance[Pb$Park=="P"] <- 0.7
##BLAISDELL to 10
Pb$Distance[Pb$Park=="B"] <- .1
head(Pb)
```

```{r park lm, echo=FALSE}
parks.lm=lm(Pb68~ Park, data=Pb)
plot(Pb68~ Park, data=Pb)
Pb.lm = lm(Total~Distance,data=Pb)
plot(Total~Distance,data=Pb)
summary(Pb.lm)
```

