---
title: "New York City Flood Risk Assessment"
author: "eve kaufman"
date: "2/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```


```{r}

filepath = "/home/CAMPUS/eakb2016/Climate_Change_Narratives/student_folders/Kaufman/1606726.csv"
filepath2 = "/home/CAMPUS/eakb2016/Climate_Change_Narratives/student_folders/Kaufman/1628915.csv"
climate_data = read.csv(filepath)
sealevel_data = read.csv(filepath2)
strDates <- as.character(climate_data$DATE)
climate_data$NewDate <- as.Date(strDates, "%Y-%m-%d")
climate_data$Month = format(as.Date(climate_data$NewDate), format = "%m")
climate_data$Year = format(climate_data$NewDate, format="%Y")

MonthlyTMAXMean = aggregate(TMAX ~ Month + Year, climate_data, mean)
MonthlyTMAXMean$YEAR = as.numeric(MonthlyTMAXMean$Year)
MonthlyTMAXMean$MONTH = as.numeric(MonthlyTMAXMean$Month)


Months = c("Temperature in January", "Temperature in February", "Temperature in March", "Temperature in April", "Temperature in May", "Temperature in June",
"Temperature in July", "Temperature in August", "Temperature in September", "Temperature in October", "Temperature in November", "Temperature in December")

TMAXresult <- NA

par(mar=c(1,1,1,1))

for (i in 1:12){
plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$MONTH==i,], ty='l', las=1, xlim=c(1940, 2020), main=Months[i])
Month.lm <- lm(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$MONTH==i,])
summary(Month.lm)
abline(coef(Month.lm), col="blue")
TMAXresult <- rbind(TMAXresult, cbind(Months[i], round(coef(Month.lm)[2], 4), round(summary(Month.lm)$coefficients[2,4],4), round(summary(Month.lm)$r.squared, 3)))
}


```



## Including Plots


```{r pressure, echo=FALSE}
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
