---
title: "Temperature Trends in Ann Arbor, MI"
author: "Lila Rubin"
date: "9/5/2020"
output: html_document
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

This blog will discuss data collected regarding temperature and precipitation in Ann Arbor, Michigan from 1891 to the present day. After displaying and analyzing the data, we will discuss what conclusions may be drawn about the area's climate trends over time.

```{r climate_data, echo=FALSE}
climate_data <-read.csv("/home/CAMPUS/lraa2020/Climate_Change_Narratives/Student_Folders/Rubin/lila_annarbor_temp_and_precip.csv")
strDates <- as.character(climate_data$DATE)
climate_data$NewDate <- as.Date(strDates, "%m/%d/%Y")
plot(TMAX~NewDate, climate_data, ty='l')
bestfitline.lm <- lm(TMAX~NewDate, climate_data)
coef(bestfitline.lm)
abline(coef(bestfitline.lm), col="purple")
```

## Plots

You can also embed plots, for example:

```{r climate, echo=FALSE}
climate_data <-read.csv("/home/CAMPUS/lraa2020/Climate_Change_Narratives/Student_Folders/Rubin/lila_annarbor_temp_and_precip.csv")
# plot(TMAX~DATE, climate_data)
# bestfitline.lm <- lm(TMAX~DATE, climate_data)
# coef(bestfitline.lm)
# abline(coef(bestfitline.lm), col="purple")
```


