---
title: "Washington County, UT PM2.5 Analysis"
author: "Anna Madison Burns"
date: "9/27/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
Burns_WashCoUt_AQ <- read_csv("/home/CAMPUS/amba2019/EA30/Climate_Change_Narratives/Data/FA20/Burns_WashCoUt_AQ.csv")
Burns_WaCoPM25_2019 <- read_csv("/home/CAMPUS/amba2019/EA30/Climate_Change_Narratives/Data/FA20/Burns_WaCoPM25_2019.csv")
Burns_WaCoPM25_2018 <- read_csv("/home/CAMPUS/amba2019/EA30/Climate_Change_Narratives/Data/FA20/Burns_WaCoPM25_2018.csv")
```

This is Anna Burns' preliminary analysis of particulate matter 2.5 levels in Washington County, Utah.

```{r}
WaCoPM25 = rbind(Burns_WashCoUt_AQ, Burns_WaCoPM25_2019, Burns_WaCoPM25_2018)
```

```{r}
#fixing dates
Date.char = as.character(WaCoPM25$Date)
WaCoPM25$Date = as.Date(Date.char, format="%m/%d/%Y")
```

```{r}
#fixing names
names(WaCoPM25)[names(WaCoPM25) == "Daily Mean PM2.5 Concentration"] <- "PM25"
```

```{r}
plot(PM25~Date, data=WaCoPM25, main="PM 2.5 Concentration in Washington County, UT", sub="1 January, 2018 to 5 October, 2020", ylab="PM2.5 in ug/m3")
fitPM <- lm(PM25~Date, data=WaCoPM25)
summary(fitPM)
coef(fitPM)
abline(coef(fitPM), col = "red", lwd = 2)
```

