---
title: "DesPlaines"
author: "Anna Madison Burns"
date: "9/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Burns_DP_Daily <- read.table("/home/CAMPUS/amba2019/EA30/Climate_Change_Narratives/Data/FA20/Burns_DP_Daily.txt", fill=TRUE)
```

# To do

- format Burns_DP_annual -> annual maximum flow rates, look at when in the year they occur and how high they are

# Formatting Daily Data

Source: https://nwis.waterdata.usgs.gov/nwis/dv?cb_00045=on&cb_00060=on&cb_00065=on&format=rdb&site_no=05527800&referred_module=sw&period=&begin_date=1838-09-01&end_date=2020-09-16

Units:
Gauge height - feet (mean)
Discharge - cubic feet per second (mean)
Precipitation - total inches (sum)

```{r}
summary(Burns_DP_Daily)
```

```{r}
colnames(Burns_DP_Daily)
```
```{r}
Burns_DP_Daily <- Burns_DP_Daily[c(-1,-2,-5,-7,-9)]
```
```{r}
colnames(Burns_DP_Daily)
```
```{r}
names(Burns_DP_Daily)[names(Burns_DP_Daily) == "V3"] <- "Date"
names(Burns_DP_Daily)[names(Burns_DP_Daily) == "V4"] <- "Gauge_Ht"
names(Burns_DP_Daily)[names(Burns_DP_Daily) == "V6"] <- "Discharge"
names(Burns_DP_Daily)[names(Burns_DP_Daily) == "V8"] <- "Precip"
```
```{r}
#this didn't work for some reason
strDates_DPD <- as.character(Burns_DP_Daily$Date)
Burns_DP_Daily$date <- as.Date(strDates_DPD, "%m/%d/%Y")
```
```{r}
Burns_DP_Daily <- Burns_DP_Daily[-c(1,2),] 
```

# Basic Analysis - Daily

```{r}
plot(Gauge_Ht~Date, data=Burns_DP_Daily, main='Des Plaines River Gauge Height (Russell, IL)', sub='July 7, 1968 to September 14, 2020', ylab='Gauge Height (feet)')
#Gauge.lm <- lm(Gauge_Ht~Date, data=Burns_DP_Daily)
#summary(Gauge.lm)
#coef(Gauge.lm)
#abline(coef(Gauge.lm), col = "purple", lwd = 2)
```

# Basic Analysis - Monthly

# Basic Analysis - Annual
