---
title: "Regional Weather Analysis Figures"
author: "Anna Madison Burns"
date: "9/18/2020"
output: html_document
---

```{r setup, include=FALSE}
library(readxl)
Burns_DP_Alternate <- read_excel("/home/CAMPUS/amba2019/EA30/Climate_Change_Narratives/Data/FA20/Burns_DesPlainesMax_Data.xlsx", 
    col_types = c("date", "numeric", "numeric"))
LakeCo <- read.csv("/home/CAMPUS/amba2019/EA30/Climate_Change_Narratives/Data/FA20/Burns_LakeCoIL_Data.csv")
require(MASS)
```

https://nwis.waterdata.usgs.gov/nwis/peak?site_no=05527800&agency_cd=USGS&format=rdb

```{r}
plot(Burns_DP_Alternate)
```

# Peak Flow

```{r}
plot(log(PeakFlow)~Date, data=Burns_DP_Alternate)
PeakFlow.lm <- lm(log(PeakFlow)~Date, data=Burns_DP_Alternate)
summary(PeakFlow.lm)
coef(PeakFlow.lm)
abline(coef(PeakFlow.lm), col = "blue", lwd=2)
```

## Assumptions

```{r}
plot(PeakFlow.lm)
boxcox(PeakFlow.lm)
```

# Peak Gauge

```{r}
plot(PeakGauge~Date, data=Burns_DP_Alternate)
PeakGauge.lm <- lm(PeakGauge~Date, data=Burns_DP_Alternate)
summary(PeakGauge.lm)
coef(PeakGauge.lm)
abline(coef(PeakGauge.lm), col = "purple", lwd=2)
```

## Assumptions

```{r}
plot(PeakGauge.lm)
boxcox(PeakGauge.lm)
```

# Peak Gauge and Flow

```{r}
plot(log(PeakFlow)~PeakGauge, data=Burns_DP_Alternate)
PeakFG.lm <- lm(log(PeakFlow)~PeakGauge, data=Burns_DP_Alternate)
summary(PeakFG.lm)
coef(PeakFG.lm)
abline(coef(PeakFG.lm), col = "green", lwd=2)
```

# Assumptions

```{r}
plot(PeakFG.lm)
boxcox(PeakFG.lm)
```

# Precipitation Data

```{r}
strDates <- as.character(LakeCo$DATE)
LakeCo$Date <- as.Date(strDates, "%m/%d/%Y")
```

```{r}
plot(PRCP~Date, data=LakeCo, ty='l')
PRCP.lm <- lm(PRCP~Date, data=LakeCo)
summary(PRCP.lm)
coef(PRCP.lm)
abline(coef(PRCP.lm), col = "purple", lwd = 2)
```

```{r}
strDates <- as.character(LakeCo$DATE)
LakeCo$Date <- as.Date(strDates, "%m/%d/%Y")
LakeCo$Month = format(as.Date(LakeCo$Date), format = "%m")
LakeCo$Year = format(as.Date(LakeCo$Date), format="%Y")
```

```{r}
MonthlyPRCP = aggregate(PRCP ~ Month + Year, data = LakeCo, sum)
MonthlyPRCP$YEAR = as.numeric(MonthlyPRCP$Year)
MonthlyPRCP$MONTH = as.numeric(MonthlyPRCP$Month)
```

```{r}
Months <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")

par(mfrow = c(3,4), mar = c(5, 4, 3, 2) + 0.1)
PRCP_Sresult <- NA

for(i in 1:12) {
  plot(PRCP~YEAR, data = MonthlyPRCP[MonthlyPRCP$MONTH == i, ], ty = 'l', las = 1, xlim = c(1901,2008), main = Months[i])
  MonthPRCP_S.lm <- lm(PRCP~YEAR, data = MonthlyPRCP[MonthlyPRCP$MONTH == i, ])
  summary(MonthPRCP_S.lm)
  
  abline(coef(MonthPRCP_S.lm), col = 'blue')
  
  PRCP_Sresult <- rbind(PRCP_Sresult, cbind(Months[i],
round(coef(MonthPRCP_S.lm)[2], 4), round(summary(MonthPRCP_S.lm)$coefficients[2,
4], 4), round(summary(MonthPRCP_S.lm)$r.squared,
3)))

}
```

```{r}
library(xtable)
PRCP_Table <- xtable(PRCP_Sresult)

names(PRCP_Table) <- c('Month','Slope','P', 'R-Sq')

print(PRCP_Table)
```



