---
title: "Aberdeen Blog"
author: "Minah Choi"
date: "2/27/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Markdown

```{r importdata}
#file="/home/CAMPUS/mmc02014/Climate_Change_Narratives/Data/SP18/choi_aberdeen station_data.csv"
file="choi_aberdeen station_data.csv"
climate_data <- read.csv(file)

strDates <- as.character(climate_data$DATE)
climate_data$NewDate <- as.Date(strDates, "%Y-%m-%d", tryFormats = c("%Y-%m-%d", "%m/%d/%Y"))
# Command didn't work, brute force method
climate_data$NewDate[2696:45597] <- as.Date(strDates[2696:45597], "%m/%d/%Y")
```


## Plot of all dates

```{r intialplot, echo=FALSE}

plot(TMAX ~ NewDate, data = climate_data)
lm(TMAX ~ NewDate, data = climate_data)
summary(lm(TMAX ~ NewDate, data = climate_data))
```


## Create Monthly Means

```{r monthlymeans}
climate_data$Month = format(as.Date(climate_data$NewDate), format = "%m")
climate_data$Year = format(climate_data$NewDate, format="%Y")
MonthlyTMAXMean = aggregate(TMAX ~ Month + Year, climate_data, mean)

MonthlyTMAXMean$YEAR = as.numeric(MonthlyTMAXMean$Year)
MonthlyTMAXMean$MONTH = as.numeric(MonthlyTMAXMean$Month)
str(MonthlyTMAXMean)

plot(MonthlyTMAXMean$TMAX, ty='l')

# I changed the name to be consistant and put it in this block
MonthlyTMINMean = aggregate(TMIN ~ Month + Year, climate_data, mean)

MonthlyTMINMean$YEAR = as.numeric(MonthlyTMINMean$Year)

MonthlyTMINMean$YEAR = as.numeric(MonthlyTMINMean$Year)
MonthlyTMINMean$MONTH = as.numeric(MonthlyTMINMean$Month)
head(MonthlyTMINMean)

```

## Including Plots

You can also embed plots, for example:

```{r allmonths, echo=FALSE}
##JAN
plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="01",], ty='p', xlim=c(1890, 2020))
Jan.lm <- lm(TMAX~YEAR, data = MonthlyTMAXMean[MonthlyTMAXMean$Month=="01",])
abline(coef(Jan.lm), col="red")
## TMIN

plot(TMIN~YEAR, data=MonthlyTMINMean[MonthlyTMINMean$Month=="01",], ty='p', xlim=c(1890, 2020))
Jan.lm <- lm(TMIN~YEAR, data = MonthlyTMINMean[MonthlyTMINMean$Month=="01",])
abline(coef(Jan.lm), col="blue")


##FEB
plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="02",], ty='l', xlim=c(1950, 2020))
Feb.lm <- lm(TMAX~YEAR, data = MonthlyTMAXMean[MonthlyTMAXMean$Month=="02",])
abline(coef(Feb.lm), col="red")

##MAR
plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="03",], ty='l', xlim=c(1950, 2020))
Mar.lm <- lm(TMAX~YEAR, data = MonthlyTMAXMean[MonthlyTMAXMean$Month=="03",])
abline(coef(Mar.lm), col="red")

##APR
plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="04",], ty='l', xlim=c(1950, 2020))
Apr.lm <- lm(TMAX~YEAR, data = MonthlyTMAXMean[MonthlyTMAXMean$Month=="04",])
abline(coef(Apr.lm), col="red")

##MAY
plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="05",], ty='l', xlim=c(1950, 2020))
May.lm <- lm(TMAX~YEAR, data = MonthlyTMAXMean[MonthlyTMAXMean$Month=="05",])
abline(coef(May.lm), col="red")

##JUN
plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="06",], ty='l', xlim=c(1950, 2020))
Jun.lm <- lm(TMAX~YEAR, data = MonthlyTMAXMean[MonthlyTMAXMean$Month=="06",])
abline(coef(Jun.lm), col="red")

##JUL
plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="07",], ty='l', xlim=c(1950, 2020))
Jul.lm <- lm(TMAX~YEAR, data = MonthlyTMAXMean[MonthlyTMAXMean$Month=="07",])
abline(coef(Jul.lm), col="red")

##AUG
plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="08",], ty='l', xlim=c(1950, 2020))
Aug.lm <- lm(TMAX~YEAR, data = MonthlyTMAXMean[MonthlyTMAXMean$Month=="08",])
abline(coef(Aug.lm), col="red")

##SEP
plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="09",], ty='l', xlim=c(1950, 2020))
Sep.lm <- lm(TMAX~YEAR, data = MonthlyTMAXMean[MonthlyTMAXMean$Month=="09",])
abline(coef(Sep.lm), col="red")

##OCT
plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="10",], ty='l', xlim=c(1950, 2020))
Oct.lm <- lm(TMAX~YEAR, data = MonthlyTMAXMean[MonthlyTMAXMean$Month=="10",])
abline(coef(Oct.lm), col="red")

##NOV
plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="11",], ty='l', xlim=c(1950, 2020))
Nov.lm <- lm(TMAX~YEAR, data = MonthlyTMAXMean[MonthlyTMAXMean$Month=="11",])
abline(coef(Nov.lm), col="red")

##DEC
plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="12",], ty='l', xlim=c(1950, 2020))
Dec.lm <- lm(TMAX~YEAR, data = MonthlyTMAXMean[MonthlyTMAXMean$Month=="12",])
abline(coef(Dec.lm), col="red")

#Months = c("January", "Febuary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
#par(mfrow=c(4,3), mar=c(5, 4, 3, 2) + 0.1)
#TMAXresult <- NA
#for (i in 1:12){plot}
#plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$MONTH==i,])
#summary(Month.lm)
```
```{r minimum}

library(xtable)
#Results <- data.frame(Month = TMINresult[c(2:13),1], TMINSlope = TMINresult[c(2:13),2],)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
