## Impacts

Connecticut’s climate is changing. The state has warmed two
to three degrees (F) in the last century. Throughout the northeastern United States, spring is arriving earlier and bringing more
precipitation, heavy rainstorms are more frequent, and summers
are hotter and drier. Sea level is rising, and severe storms increasingly cause floods that damage property and infrastructure.
In the coming decades, changing the climate is likely to increase
flooding, harm ecosystems, disrupt farming, and increase some
risks to human health.

[EPA Snapshot](https://19january2017snapshot.epa.gov/sites/production/files/2016-09/documents/climate-change-cu.pdf)

## State Adaptation / Mitigation Plans

Connecticut established a Governor’s Steering Committee on Climate Change in 2002. On June 2, 2008, the Connecticut legislature set greenhouse gas emissions reductions goals for the state (An Act Concerning Connecticut Global Warming Solutions; Public Act No. 08-98) and also called for the development of an Adaptation Subcommittee to identify climate impacts anticipated for the state and recommend actions to adapt to those impacts. In July 2013, the state finalized its adaptation plan, the Connecticut Climate Preparedness Plan. The state also periodically issues progress reports highlighting actions taken to implement the 2008 Global Warming Solutions Act and the last progress report — Taking Action on Climate Change 2014 Progress Report — was released in June 2014.

[Source: Georgetown Climate Center] (https://www.georgetownclimate.org/adaptation/state-information/connecticut/overview.html)