\documentclass{article}

\title{SOP 84: Obtaining Climate Records}
\author{Marc Los Huertos}

\begin{document}
\maketitle

\section{Terrestrial Meteorological Data}




\subsection{Sources of Data}


\subsection{Interface Choices}

\subsection{Evaluating Records}

\subsection{Export Options}


\section{Sea Surface Temperature Data}

\section{Satellite Data}

\section{Ice-Core Data}



\end{document}