---
title: "PlayingWithMonthProcessing"
author: "Leah Ho-Israel"
date: "2/7/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
plot(MonthlyMeanTMIN$TMIN, ty='l')

plot(MonthlyMeanTMIN$TMIN[MonthlyMeanTMIN$Month=="12"], ty='l')

plot(TMIN~YEAR, data=MonthlyMeanTMIN[MonthlyMeanTMIN$Month=="12",], ty='l') 
Dec.lm <- lm(TMIN~YEAR, data=MonthlyMeanTMIN[MonthlyMeanTMIN$Month=="12",])
summary(Dec.lm)

abline(coef(Dec.lm), col="red")

```

```{r Playing with Loops}
#+ results='asis', echo = FALSE
for (i in 1:5) {
    cat("## This is a heading for ", i, "\n")
    cat("<!-- This is a comment for ", i, "-->\n")
    print(i)    
}
```

```{r}
#Plotting z_1 against z_2 according to the names x_1
x_1 <- c("1", "2", "3", "4", "5", "6","7", "8", "9", "10", "11", "12")
z_1 <- rnorm(10, 70) 
z_2 <- rnorm(10, 1.7)
A <- data.frame(x_1, z_1, z_2)

data_1 <- A[A$x_1 == "1", ]    # deleting which() makes it cleaner
with(data_A1, plot(z_2, z_1))    # you can also use with() to save typing
```

```{r}
x_1 <- c("A1", "A1", "A1", "B10", "B10", "B10","B10", "C100", "C100", "C100")
z_1 <- rnorm(10, 70) 
z_2 <- rnorm(10, 1.7)
A <- data.frame(x_1, z_1, z_2)

data_A1 <- A[A$x_1 == "A1", ]    # deleting which() makes it cleaner
with(data_A1, plot(z_2, z_1)) 

for (i in unique(A$x_1)) {   
    plot(A[A$x_1==i, "z_2"], A[A$x_1==i, "z_1"])  # z_2 on x, z_1 on y 
}   # Works!!!
```

```{r}

data.frame("1", "2", "3", "4", "5", "6","7", "8", "9", "10", "11", "12")
{month=c("1", "2", "3", "4", "5", "6","7", "8", "9", "10", "11", "12")
  temp= (10 20 30 40 50 60 70 80 90 100)}

for (i in c("1", "2", "3", "4", "5", "6","7", "8", "9", "10", "11", "12"))
  print(month$temp)

```


