---
title: "Regional Analysis - Snow"
author: "Olivia"
date: "9/16/2020"
output: html_document
---
## This is a test document for snow data from Chicago Midway Airport
## it will serve to show trends in snowfall, as a result of warming trends...

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r readdata, echo=FALSE}


# Olivia, you'll want to use choose.file() to find your path and paste it below, then uncomment it so it over-writes mine...
#file.choose()
filepath = "/home/CAMPUS/ocma2018/Climate_Change_Narratives/Data/FA20/olivia_chicagomidway_data.csv"
climate_data = read.csv(filepath) 
strDates <- as.character(climate_data$DATE)
climate_data$NewDate <- as.Date(strDates, "%Y-%m-%d")
```


## TMAX graph


```{r plotdailydata}
plot(TMAX~NewDate, data=climate_data, ty='l')



TMAX.lm = lm(TMAX ~ NewDate, data=climate_data) 


slopeintercept = coef(TMAX.lm)
abline(coef(TMAX.lm), col = 'pink') 
```


## Types of Weather

```{r weatherdailydata}
filepath = "/home/CAMPUS/ocma2018/Climate_Change_Narratives/Data/FA20/olivia_snow_data.csv" 
read.csv("/home/CAMPUS/ocma2018/Climate_Change_Narratives/Data/FA20/olivia_snow_data.csv")
his  

