---
title: "Kylie's Topic of Interest"
author: "Kylie"
date: "2/11/2019"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Guangzhou, China Temperature Graph 
```{r}
#preparing and reading CSV file 
read.csv("/home/CAMPUS/hwab2018/Climate_Change_Narratives/student_folders/Wong/kyliewong_guangzhou_data.csv")
climate_data <- read.csv("/home/CAMPUS/hwab2018/Climate_Change_Narratives/student_folders/Wong/kyliewong_guangzhou_data.csv")
head(climate_data)
str(climate_data)
climate_data$TMAX
plot(TMAX~DATE, climate_data)
min(climate_data$TMAX)
min(climate_data$TMAX, na.rm=T)
```


```{r, echo = FALSE}
##Changing dates
climate_data$TMAX[climate_data$TMAX==-9999] = NA
climate_data$TMIN[climate_data$TMIN==-9999] = NA
plot(TMAX~DATE, climate_data[1:1835,], ty='l')
str(climate_data)
strDates <- as.character(climate_data$DATE)
climate_data$NewDate <- as.Date(strDates, "%Y-%m-%d")
plot(TMAX~NewDate, climate_data[1:1835,], ty='l')
```


```{r, echo = FALSE}
##Preparing the monthly average plots 
lm(TMAX ~ NewDate, data=climate_data)
summary(lm(TMAX ~ NewDate, data=climate_data))
climate_data$Month = format(as.Date(climate_data$NewDate), format = "%m")
climate_data$Year = format(climate_data$NewDate, format="%Y")
MonthlyTMAXMean = aggregate(TMAX ~ Month + Year, climate_data, mean)
MonthlyTMAXMean$YEAR = as.numeric(MonthlyTMAXMean$Year)
MonthlyTMAXMean$MONTH = as.numeric(MonthlyTMAXMean$Month)
str(MonthlyTMAXMean)
plot(MonthlyTMAXMean$TMAX, ty='l')
```


```{r, echo = FALSE}
##May Vector 
plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="05",], ty='l', xlim=c(1950, 2020))
May.lm <- lm(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="05",])
summary(May.lm)
abline(coef(May.lm), col="red")
MonthlyTMINMean = aggregate(TMIN ~ Month + Year, climate_data, mean)
MonthlyTMINMean$YEAR = as.numeric(MonthlyTMINMean$Year)
MonthlyTMINMean$YEAR = as.numeric(MonthlyTMINMean$Year)
MonthlyTMINMean$MONTH = as.numeric(MonthlyTMINMean$Month)
head(MonthlyTMINMean)
```


```{r, echo = FALSE}
##Monthly averages of daily minimum temperatures
Months = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
par(mfrow = c(4, 3), mar = c(5, 4, 3, 2) + 0.1)
TMAXresult <- NA
for (i in 1:12) {
plot(TMAX ~ YEAR, data = MonthlyTMAXMean[MonthlyTMAXMean$MONTH == i, ], ty = "l", las = 1, xlim = c(1940, 2020), main = Months[i])
Month.lm <- lm(TMAX ~ YEAR, data = MonthlyTMAXMean[MonthlyTMAXMean$MONTH == i, ])
summary(Month.lm)
abline(coef(Month.lm), col = "red")
TMAXresult <- rbind(TMAXresult, cbind(Months[i],
round(coef(Month.lm)[2], 4), round(summary(Month.lm)$coefficients[2,4], 4), round(summary(Month.lm)$r.squared, 3)))
}

plot(MonthlyTMINMean$TMIN, ty='l')


```


