---
title: "A Blog Thing"
author: "Toni Anderson"
date: "2/11/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##Initial Climate Data

```{r}
##Read CSV Data
filepath= "/home/CAMPUS/ttab2018/Climate_Change_Narratives/student_folders/Anderson/tonianderson_burbank_realdata.csv"
climate_data = read.csv(filepath)
head(climate_data)
str(climate_data)
names(climate_data)

##Fix Dates
strDates <- as.character(climate_data$DATE)
climate_data$NewDate <- as.Date(strDates, "%m/%d/%Y")

##Plot Data
plot(TMAX~NewDate, climate_data, ty='l', main="TMAX(Degrees Celcius) vs. Time(Years)", xlab="Time(Years)", ylab="TMAX(Degrees Celcius)", col.main="black", col.lab="red" )
c <- coef(lm(TMAX~NewDate, climate_data))
abline(c, col="red")

##TMIN
plot(TMIN~NewDate, climate_data, ty='l', main="TMIN(Degrees Celcius) vs. Time(Years)", xlab="Time(Years)", ylab="TMIN(Degrees Celcius)", col.main="black", col.lab="blue" )
c <- coef(lm(TMIN~NewDate, climate_data))
abline(c, col="blue")
```

##Monthly Data Max and Mins

```{r}
## Define Shit
lm(TMAX~NewDate, data=climate_data)
summary(lm(TMAX~NewDate, data=climate_data))

##Monthly Averages
climate_data$Month = format(as.Date(climate_data$NewDate), format="%m")
climate_data$Year = format(as.Date(climate_data$NewDate), format="%Y")
MonthlyTMAXMean = aggregate(TMAX ~ Month +Year, climate_data, mean)
MonthlyTMAXMean$YEAR = as.numeric(MonthlyTMAXMean$Year)
MonthlyTMAXMean$MONTH = as.numeric(MonthlyTMAXMean$Month)
str(MonthlyTMAXMean)
plot(MonthlyTMAXMean$TMAX, ty='l')

##Plot May
plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="05",], ty='l', xlim=c(1950, 2020), main="May TMAX(Degrees Celcius) vs. Time(Years)", xlab="Time(Years)", ylab="TMAX(Degrees Celcius)", col.main="black", col.lab="blue")
May.lm <- lm(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="05",])
summary(May.lm)
abline(coef(May.lm), col="red")

##TMIN Definitions
plot(TMIN~NewDate, climate_data, ty='l', main="TMIN(Degrees Celcius) vs. Time(Years)", xlab="Time(Years)", ylab="TMIN(Degrees Celcius)", col.main="black", col.lab="blue" )
c <- coef(lm(TMIN~NewDate, climate_data))
abline(c, col="red")
MonthlyTMINMean = aggregate(TMIN ~ Month +Year, climate_data, mean)
MonthlyTMINMean$YEAR = as.numeric(MonthlyTMINMean$Year)
MonthlyTMINMean$MONTH = as.numeric(MonthlyTMINMean$Month)
head(MonthlyTMINMean)


##Every Month! Come back and do 1 by 1
Months = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
par(mfrow = c(3, 4), mar = c(5, 4, 3, 2) + 0.1 )
TMAXresult <- NA 
for (i in 1:12) {
  plot(TMAX ~ YEAR, data =  MonthlyTMAXMean[MonthlyTMAXMean$MONTH == i, ], ty = "l", las = 1, xlim = c(1940, 2020), ylim=c(15, 35),main = Months[i])
Month.lm <- lm(TMAX ~ YEAR, data = MonthlyTMAXMean[MonthlyTMAXMean$MONTH == i, ])
summary(Month.lm)
abline(coef(Month.lm), col = "red")
TMAXresult <- rbind(TMAXresult, cbind(Months[i], round(coef(Month.lm)[2], 4), round(summary(Month.lm)$coefficients[2, 4], 4), round(summary(Month.lm)$r.squared, 3)))
}

##Daily Mins (Decide which months [Oct, Nov, Dec; summer too?]
Months = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
par(mfrow = c(3, 4), mar = c(5, 4, 3, 2) + 0.1 )
TMINresult <- NA 
for (i in 1:12) {
  plot(TMIN ~ YEAR, data =  MonthlyTMINMean[MonthlyTMINMean$MONTH == i, ], ty = "l", las = 1, xlim = c(1940, 2020), ylim=c(0, 20),main = Months[i])
Month.lm <- lm(TMIN ~ YEAR, data = MonthlyTMINMean[MonthlyTMINMean$MONTH == i, ])
summary(Month.lm)
abline(coef(Month.lm), col = "red")
TMINresult <- rbind(TMINresult, cbind(Months[i], round(coef(Month.lm)[2], 4), round(summary(Month.lm)$coefficients[2, 4], 4), round(summary(Month.lm)$r.squared, 3)))
}

```
```{r}
##Precipitation Data (Initial Data)
filepath= "/home/CAMPUS/ttab2018/Climate_Change_Narratives/student_folders/Anderson/tonianderson_burbank_realdata.csv"
climate_data = read.csv(filepath)
head(climate_data)
str(climate_data)
names(climate_data)

##Fix Dates
strDates <- as.character(climate_data$DATE)
climate_data$NewDate <- as.Date(strDates, "%m/%d/%Y")

##Plot Data
plot(PRCP~NewDate, climate_data, ty='l', ylim=c(0, 300), main="Precipitation vs. Time(Years)", xlab="Time(Years)", ylab="Precipitation Celcius)", col.main="black", col.lab="green" )
c <- coef(lm(PRCP~NewDate, climate_data))
abline(c, col="red")

```
```{r}
##Precipitaion Data (Get sum, then create monthly plots)
## Define Shit
lm(PRCP~NewDate, data=climate_data)
summary(lm(PRCP~NewDate, data=climate_data))

##Monthly Sums
climate_data$Month = format(as.Date(climate_data$NewDate), format="%m")
climate_data$Year = format(as.Date(climate_data$NewDate), format="%Y")
MonthlyPRCPSum = aggregate(PRCP ~ Month +Year, climate_data, sum)
MonthlyPRCPSum$YEAR = as.numeric(MonthlyPRCPSum$Year)
MonthlyPRCPSum$MONTH = as.numeric(MonthlyPRCPSum$Month)
str(MonthlyPRCPSum)


##Plot May
plot(PRCP~YEAR, data=MonthlyPRCPSum[MonthlyPRCPSum$Month=="05",], ty='l', xlim=c(1950, 2020), main="May Precipitation vs. Time(Years)", xlab="Time(Years)", ylab="Precipitation", col.main="black", col.lab="blue")
May.lm <- lm(PRCP~YEAR, data=MonthlyPRCPSum[MonthlyPRCPSum$Month=="05",])
summary(May.lm)
abline(coef(May.lm), col="red")


##Every Month! Come back and do 1 by 1
Months = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
par(mfrow = c(3, 4), mar = c(5, 4, 3, 2) + 0.1 )
PRCPresult <- NA 
for (i in 1:12) {
plot(PRCP ~ YEAR, data =  MonthlyPRCPSum[MonthlyPRCPSum$MONTH == i, ], ty = "l", las = 1, xlim = c(1940, 2020), ylim=c(0, 400), main = Months[i], xlab="Total Precipation", ylab="Year", col.main="black", col.lab="green" )
Month.lm <- lm(PRCP ~ YEAR, data = MonthlyPRCPSum[MonthlyPRCPSum$MONTH == i, ])
summary(Month.lm)
abline(coef(Month.lm), col = "red")
PRCPresult <- rbind(PRCPresult, cbind(Months[i], round(coef(Month.lm)[2], 4), round(summary(Month.lm)$coefficients[2, 4], 4), round(summary(Month.lm)$r.squared, 3)))
}

```
##TMAX Fall
```{r}
##TMAX Months

#October
plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="10",], ty='l', xlim=c(1950, 2020), main="Oct TMAX(Degrees Celcius) vs. Time(Years)", xlab="Time(Years)", ylab="TMAX(Degrees Celcius)", col.main="black", col.lab="red")
Oct.lm <- lm(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="10",])
summary(Oct.lm)
abline(coef(Oct.lm), col="red")
#November
plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="11",], ty='l', xlim=c(1950, 2020), main="Nov TMAX(Degrees Celcius) vs. Time(Years)", xlab="Time(Years)", ylab="TMAX(Degrees Celcius)", col.main="black", col.lab="red")
Nov.lm <- lm(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="11",])
summary(Nov.lm)
abline(coef(Nov.lm), col="red")
#December
plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="12",], ty='l', xlim=c(1950, 2020), main="Dec TMAX(Degrees Celcius) vs. Time(Years)", xlab="Time(Years)", ylab="TMAX(Degrees Celcius)", col.main="black", col.lab="red")
Dec.lm <- lm(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$Month=="12",])
summary(Dec.lm)
abline(coef(Dec.lm), col="red")
#As one!
Months = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
par(mfrow = c(2, 3), mar = c(5, 4, 3, 2) + 0.1 )
TMAXresult <- NA 
for (i in 10:12) {
  plot(TMAX ~ YEAR, data =  MonthlyTMAXMean[MonthlyTMAXMean$MONTH == i, ], ty = "l", las = 1, xlim = c(1940, 2020), ylim=c(15, 35), xlab="Time (Years)", ylab="TMAX (Degrees Celcius)", col.lab="red", main = Months[i])
Month.lm <- lm(TMAX ~ YEAR, data = MonthlyTMAXMean[MonthlyTMAXMean$MONTH == i, ])
summary(Month.lm)
abline(coef(Month.lm), col = "red")
TMAXresult <- rbind(TMAXresult, cbind(Months[i], round(coef(Month.lm)[2], 4), round(summary(Month.lm)$coefficients[2, 4], 4), round(summary(Month.lm)$r.squared, 3)))
}
```

```{r}
##TMIN Months

#October
plot(TMIN~YEAR, data=MonthlyTMINMean[MonthlyTMINMean$Month=="05",], ty='l', xlim=c(1950, 2020), main="Oct TMIN(Degrees Celcius) vs. Time(Years)", xlab="Time(Years)", ylab="TMIN(Degrees Celcius)", col.main="black", col.lab="blue")
Oct.lm <- lm(TMIN~YEAR, data=MonthlyTMINMean[MonthlyTMINMean$Month=="10",])
summary(Oct.lm)
abline(coef(Oct.lm), col="blue")
#November
plot(TMIN~YEAR, data=MonthlyTMINMean[MonthlyTMINMean$Month=="11",], ty='l', xlim=c(1950, 2020), main="Nov TMIN(Degrees Celcius) vs. Time(Years)", xlab="Time(Years)", ylab="TMIN(Degrees Celcius)", col.main="black", col.lab="blue")
Nov.lm <- lm(TMIN~YEAR, data=MonthlyTMINMean[MonthlyTMINMean$Month=="11",])
summary(Nov.lm)
abline(coef(Nov.lm), col="blue")
#December
plot(TMIN~YEAR, data=MonthlyTMINMean[MonthlyTMINMean$Month=="12",], ty='l', xlim=c(1950, 2020), main="Dec TMIN(Degrees Celcius) vs. Time(Years)", xlab="Time(Years)", ylab="TMIN(Degrees Celcius)", col.main="black", col.lab="blue")
Dec.lm <- lm(TMIN~YEAR, data=MonthlyTMINMean[MonthlyTMINMean$Month=="12",])
summary(Dec.lm)
abline(coef(Dec.lm), col="blue")
#As one!
Months = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
par(mfrow = c(2, 3), mar = c(5, 4, 3, 2) + 0.1 )
TMINresult <- NA 
for (i in 10:12) {
  plot(TMIN ~ YEAR, data =  MonthlyTMINMean[MonthlyTMINMean$MONTH == i, ], ty = "l", las = 1, xlim = c(1940, 2020), ylim=c(0, 20),xlab="Time (Years)", ylab="TMIN (Degrees Celcius)", col.lab="blue", main = Months[i])
Month.lm <- lm(TMIN ~ YEAR, data = MonthlyTMINMean[MonthlyTMINMean$MONTH == i, ])
summary(Month.lm)
abline(coef(Month.lm), col = "blue")
TMINresult <- rbind(TMINresult, cbind(Months[i], round(coef(Month.lm)[2], 4), round(summary(Month.lm)$coefficients[2, 4], 4), round(summary(Month.lm)$r.squared, 3)))
}
```

```{r}
##Precipitation Months

#October
plot(PRCP~YEAR, data=MonthlyPRCPSum[MonthlyPRCPSum$Month=="10",], ty='l', xlim=c(1950, 2020), main="Oct Precipitation vs. Time(Years)", xlab="Time(Years)", ylab="Precipitation", col.main="black", col.lab="green")
Oct.lm <- lm(PRCP~YEAR, data=MonthlyPRCPSum[MonthlyPRCPSum$Month=="10",])
summary(Oct.lm)
abline(coef(Oct.lm), col="green")
#November
plot(PRCP~YEAR, data=MonthlyPRCPSum[MonthlyPRCPSum$Month=="11",], ty='l', xlim=c(1950, 2020), main="Nov Precipitation vs. Time(Years)", xlab="Time(Years)", ylab="Precipitation", col.main="black", col.lab="green")
Nov.lm <- lm(PRCP~YEAR, data=MonthlyPRCPSum[MonthlyPRCPSum$Month=="11",])
summary(Nov.lm)
abline(coef(Nov.lm), col="green")
#December
plot(PRCP~YEAR, data=MonthlyPRCPSum[MonthlyPRCPSum$Month=="12",], ty='l', xlim=c(1950, 2020), main="Dec Precipitation vs. Time(Years)", xlab="Time(Years)", ylab="Precipitation", col.main="black", col.lab="green")
Dec.lm <- lm(PRCP~YEAR, data=MonthlyPRCPSum[MonthlyPRCPSum$Month=="12",])
summary(Dec.lm)
abline(coef(Dec.lm), col="green")

#As one
Months = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
 par(mfrow = c(2, 3), mar = c(5, 4, 3, 2) + 0.1 )
 PRCPresult <- NA 
 for (i in 10:12) {
plot(PRCP ~ YEAR, data =  MonthlyPRCPSum[MonthlyPRCPSum$MONTH == i, ], ty = "l", las = 1, xlim = c(1940, 2020), ylim=c(0, 300), main = Months[i], xlab="Year", ylab="Total Precipitation", col.main="black", col.lab="green" )
Month.lm <- lm(PRCP ~ YEAR, data = MonthlyPRCPSum[MonthlyPRCPSum$MONTH == i, ])
summary(Month.lm)
abline(coef(Month.lm), col = "green")
PRCPresult <- rbind(PRCPresult, cbind(Months[i], round(coef(Month.lm)[2], 4), round(summary(Month.lm)$coefficients[2, 4], 4), round(summary(Month.lm)$r.squared, 3)))
}
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
