---
title: "Microplastics in Lettuce: Results"
author: "Susannah Budd"
date: "4/22/2019"
output: 
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Results
```{r warning=FALSE, message=FALSE, echo=FALSE} 
knitr::opts_chunk$set(message=FALSE, warning=FALSE, fig.height=4, fig.width=5, fig.align="center")
# Data in two numeric vectors
# ++++++++++++++++++++++++++
# Microplastics in Bagged Lettuce
Bagged <-c(57.500, 41.625, 35.625, 30.000, 33.750)
# Microplastics in Unbagged Lettuce
Unbagged <-c(21.625, 37.125, 33.875, 37.5000, 33.750)
# Create a data frame
bagged_unbagged <- data.frame(Group = rep(c("Bagged", "Unbagged"), each = 5), Microplastics = c(Bagged,  Unbagged))
```

```{r warning=FALSE, message=FALSE, echo=FALSE} 
knitr::opts_chunk$set(message=FALSE, warning=FALSE, fig.height=4, fig.width=5, fig.align="center")
library("knitr")
kable(bagged_unbagged[1:10,], caption="Microplastics in Bagged and Unbagged Lettuce")
```

```{r warning=FALSE, message=FALSE, echo=FALSE} 
knitr::opts_chunk$set(message=FALSE, warning=FALSE, fig.height=4, fig.width=5, fig.align="center")
##Box Plot
library("ggpubr")
ggboxplot(bagged_unbagged, x = "group", y = "microplastics", 
          color = "group", palette = c("#00AFBB", "#E7B800"),
          order = c("bagged", "unbagged"),
          ylab = "# Microplastics", xlab = "Groups")
```

###Normality Tests \

The data collection yielded five replicates and five pseduo-replicates for both bagged and unbagged lettuce, as two bagged and unbagged heads were purchased at each store

```{r warning=FALSE, message=FALSE, echo=FALSE} 
knitr::opts_chunk$set(message=FALSE, warning=FALSE, fig.height=4, fig.width=5, fig.align="center")
##Q-Q Plot Bagged
library("ggpubr")
ggqqplot(Bagged)
```

```{r include=FALSE}
##Shapiro-Wilk normality test Bagged
shapiro.test(Bagged)
```

```{r warning=FALSE, message=FALSE, echo=FALSE} 
knitr::opts_chunk$set(message=FALSE, warning=FALSE, fig.height=4, fig.width=5, fig.align="center")
##Q-Q Plot Unbagged
library("ggpubr")
ggqqplot(Unbagged)
```

```{r include=FALSE}
##Shapiro-Wilk normality test Unbagged
shapiro.test(Unbagged)
```

```{r warning=FALSE, message=FALSE, echo=FALSE} 
knitr::opts_chunk$set(message=FALSE, warning=FALSE, fig.height=4, fig.width=5, fig.align="center")
#Paired Samples Wilcoxon Test
wilcox.test(Microplastics ~ Group, data = bagged_unbagged, paired = TRUE)
#Paired Samples T-Test
t.test(Bagged, Unbagged, var.equal = TRUE)
```

