---
title: "Draft Blog"
author: "Emily Tomz"
date: "12/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Open the file

```{r read file}
climate_data <- read.csv("/home/CAMPUS/erta2018/Climate_Change_Narratives/student_folders/Tomz/Tomz_Blog_v0_files/1957996_modified.csv")
summary(climate_data)
head(climate_data)
str(climate_data)
names(climate_data)
```



## Re-format Dates

```{r dates reformatting}
strDates <- as.character(climate_data$DATE)
climate_data$NewDate <- as.Date(strDates, "%m/%d/%Y")
head(climate_data)
```




## Maximum Temperature over Time

```{r data, echo=FALSE}
plot(TMAX ~ NewDate, data = climate_data, ty = "l", xlab = "Date", ylab = "Degrees Celcius",
     main = "Maximum Daily Temperature, Zurich, Switzerland")
TMAX.lm <- lm(TMAX ~ NewDate, data = climate_data)
summary(TMAX.lm)
abline(coef(TMAX.lm), col = "red")
#legend(1910, -10, col = c(1), coef(TMAX.lm))
```
The p-value is very small, so we reject the null hypothesis. So, it is unlikely that this trend occured only by chance. From the regression, it's evident that the temperature is changing over time. It is decreasing with a slope of -1.416x10^-5 degrees C per year.


## Monthly Means

```{r monthly means}
climate_data$Month = format(as.Date(climate_data$NewDate), format = "%m")
climate_data$Year = format(climate_data$NewDate, format = "%Y")

MonthlyTMAXMean = aggregate(TMAX ~ Month + Year, climate_data, mean)

MonthlyTMAXMean$YEAR = as.numeric(MonthlyTMAXMean$Year)
MonthlyTMAXMean$MONTH = as.numeric(MonthlyTMAXMean$Month)
```
