---
title: "Washington DC Temperature Line Graphics"
author: "Jacob Greene"
date: "9/5/2020"
output: html_document
---
file.choose()
read.csv("/home/CAMPUS/jagc2019/JacobGreene_WashingtonDC_Data.csv")
climate_data <- read.csv("/home/CAMPUS/jagc2019/JacobGreene_WashingtonDC_Data.csv")
strDates <- as.character(climate_data$DATE)
climate_data$NewDate <- as.Date(strDates, "%Y-%m-%d")
plot(TMAX~NewDate, climate_data,type='l', main= "Washington D.C. Daily Temperature Maximum vs Time", xlab= "Time", ylab= "Daily Temperature Maximum (C)")
bestfitline.lm = lm(TMAX~NewDate, data = climate_data)
summary(bestfitline.lm)
coef(bestfitline.lm)
abline(coef(bestfitline.lm), col="red", lwd=2)

plot(TMIN~NewDate, climate_data,type='l', main= "Washington D.C. Daily Temperature Minimum vs Time", xlab= "Time ", ylab= "Daily Temperature Minimum (C)")
TMINbestlinefit.lm=lm(TMIN~NewDate, data = climate_data)
abline(coef(TMINbestlinefit.lm), col= "red",lwd=2)
summary(TMINbestlinefit.lm)

climate_data$Month = format(as.Date(climate_data$NewDate),format="%m")
climate_data$Year = format(climate_data$NewDate,format= "%Y")
MonthlyTMAXMean = aggregate(TMAX~Month+Year,climate_data,mean)
MonthlyTMAXMean$YEAR = as.numeric(MonthlyTMAXMean$Year)
MonthlyTMAXMean$MONTH= as.numeric(MonthlyTMAXMean$Month)
str(MonthlyTMAXMean)
plot(MonthlyTMAXMean$TMAX,type = "l")
par(mfrow=c(1,1))
plot(TMAX~YEAR, data = MonthlyTMAXMean[MonthlyTMAXMean$Month=="02",], ty='l', xlim= c(1950, 2020),main= "Feburary Monthly Temperature Maximum Means vs Time" )
Feb.lm <- lm(TMAX~YEAR, data = MonthlyTMAXMean[MonthlyTMAXMean$Month=="02",])
summary(Feb.lm)
abline(coef(Feb.lm),col= "red")


Months = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
par(mfrow=c(4,3), mar=c(5, 4, 3, 2) + 0.1)
TMAXresult <- NA
for (i in 1:12){
  plot(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$MONTH==i,], ty='l', las=1, xlim=c(1950, 2020), main=Months[i])
  Month.lm <- lm(TMAX~YEAR, data=MonthlyTMAXMean[MonthlyTMAXMean$MONTH==i,])
  summary(Month.lm)
  abline(coef(Month.lm), col="red")
  TMAXresult <- rbind(TMAXresult, cbind(Months[i], round(coef(Month.lm)[2], 4),round(summary(Month.lm)$coefficients[2,4],4),round(summary(Month.lm)$r.squared, 3)))
}


MonthlyPRCP = aggregate(PRCP~Month+Year,climate_data,sum)
MonthlyPRCP$YEAR = as.numeric(MonthlyPRCP$Year)
MonthlyPRCP$MONTH= as.numeric(MonthlyPRCP$Month)
plot(PRCP~YEAR, data= MonthlyPRCP, main= "Monthly Precipitation Totals vs Time")
PRCP.lm <-lm(PRCP~YEAR, data= MonthlyPRCP)
summary(PRCP.lm)
abline(coef(PRCP.lm), col="red", lwd= "2")
