---
title: "An Analysis of Hazardous Fuel Treatment Locations in California"
author: "Sabrina Wilk"
date: "10/9/2018"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## HEADER   


Since becoming a stand-alone category in the national fire management budget in 2001, hazardous fuel treatment has emerged as a popular topic of debate and research. Many questions have arisen, such as: How is hazardous fuel best treated? Where should efforts be concentrated? To what extent can hazardous fuel treatment reduce fire and fire suppression costs? This article aims to describe the history of human impact on fuel load, to review the effectiveness of fuel treatment methods, and to analyze where fuel management efforts are concentrated on California state-protected lands.

Hazardous fuel treatment is one of four categories in the national fire management budget, along with categories channeled toward suppression, prevention, and miscellaneous costs. Hazardous fuels are defined as “live and dead vegetation that has accumulated and increases the likelihood of unusually large wildland fires” (Cal Fire). Fuel treatment largely rose in importance because of previous fire management techniques that suppressed natural fire regimes. In 2001, it became an independent category in the federal budget (Hoover 2017).

For most of the twentieth century, firefighting organizations suppressed fires to the maximum degree possible. The Forest Service, founded in 1905, was besieged by public desire for protection from wildfires after multiple deadly fires in the late 1800s and early 1900s. Headed by Gifford Pinchot and later Henry S. Graves, the FS responded by establishing standardized fire suppression practices (Williams 2005).
However, later in the 1900s, the realization that most ecosystems needed some sort of fire regime to maintain vegetation health put an end to the ‘absolute suppression’ mindset. Fire science programs discerned that wildfire was not a negative disturbance to ecosystems; rather, it was part of a natural cycle that allowed plant communities to regenerate as needed. The Forest Service, along with other fire organizations that had followed its lead, was therefore forced to backtrack. Decades of fire suppression had resulted in a lack of fire’s natural ‘clean-up’ process in forests, leading to higher tree density, reduced tree size, and increased amounts of understory vegetation. When a fire sparked, the dense vegetation acted as fuel, with flames racing through the understory and climbing up the small, crowded trees.

This biomass ignition material became known as ‘fuel load’ by firefighters, and the easiest way the Forest Service could reduce it was to let fires burn through it. Therefore, rather than shunning fire, management agencies began to allow low-intensity fires to burn and even initiated controlled burns in fire-prone or high-fuel load areas. In California, where low-intensity, high-frequency fire regimes are common, controlled burns and mechanical treatments were particularly critical. Not only did fuel treatments promote regular flora regeneration when done correctly; they also kept fires at low-intensity, preserving ecosystem health and citizen safety by preventing larger, more destructive fires. 

Fuel treatment at the federal level rose in importance because of increasing fire suppression costs, which in fiscal years 2008-2017 averaged $3.7 billion annually (Hoover 2017). It was hoped that by removing fuel loads, fire intensity in the following fire season would be reduced, consequently lowering the cost of fire suppression tactics. Suppression costs therefore somewhat dictate where fuel load treatments are concentrated: for example, wildland-urban interface areas (WUIs), where residential areas meet forests, are high-priority treatment zones (Cal Fire).

Understanding how and where fuel treatments are carried out, and whether their locations and methodology can be strategized more efficiently, is an important aspect to improving fuel treatment effectiveness. Many studies have been conducted on the effectiveness and longevity of specific fuel treatment methods (Stephens et al 2009, Keeley 2018). A large-scale study on current areas of fuel treatments, paired with future fire data, can further determine whether fuel reduction efforts are driving lowered need for fire suppression.

To gain a better understanding of what factors determine where California’s fuel treatments are currently focused, we analyzed locations of fuel reduction efforts on state lands prior to 2017. We used Geographic Information Systems (GIS) to map fuel treatments. More specifically, we mapped where controlled burns and mechanical treatments were performed on state Direct Protection Areas (DPAs) in relation to WUIs and fires that occurred prior to 2007. We expected that controlled burns would take up more area than mechanical treatments. We also expected that both treatment types would be significantly higher near WUIs and previous fire sites than non-WUIs and non-fire sites.


## Methods
We accessed GIS layers of controlled burn and mechanical treatment data for the state of California, as well as fires prior to 2007, from the Forest Service website. Using the controlled burns and mechanical treatments layers, we calculated percentage of land treated with burns or mechanical, respectively. To find the total area of fuel treatment (in square meters) on state DPAs, we first selected the ‘state’ group from the Group DPAs layer. After selecting the ‘state’ group, we intersected the layers of controlled burns and DPA groups, then mechanical treatments and DPA groups. We named the new layers ‘State Burns’ and ‘State Mechanical.’ We intersected ‘State Burns’ and ‘State Mechanical’ to find areas where controlled burns and mechanical treatments had both been performed, and named this layer ‘State Burns Mechanical Overlap.’


We accessed data on WUIs in California from the Forest Service website. To calculate total area of burns and mechanical treatments near WUIs, we created a 400m buffer around the WUI layer and selected for burns and treatments with any part of their boundaries intersecting the buffer layer. This may result in a generous estimate of fuel treatment area close to WUIs because some of the treatment areas were as large as 44,686.5 km2, and only a small section of treatment areas needed to touch the WUI buffer to be included in the calculations.


To calculate total area of fuel treatments intersecting areas of previous fires, we selected for burns and mechanical treatments that intersected with the previous fires layer. This again may result in a generous estimate of treatment area close to previous fires, because only a small section of treatment areas needed to intersect the previous fires layer.


Lastly, we selected fuel treatments that were both near WUIs and intersecting with previous fire sites to find amount of overlap between the two. We then calculated how much of the overlap accounted for total area of burns and mechanical treatments near to WUIs, and how much of the overlap accounted for total area of burns and mechanical treatments intersecting with previous fire sites.


## Results 
State DPAs in California occupied 124,646,654.9 km2, with 3,903,519 km2 (3.1%) of that being treated for hazardous fuels. Between total area of treatment types (controlled burns and mechanical), controlled burns were conducted on the majority of treated land area, with 98.5% taken up by burns and the remaining 1.5% taken by mechanical treatments. Areas that were both burned and treated mechanically took up .1% of total treatment area.




Table 1. Fuel treatments in relation to WUIs and previous fires.
	Within 400m of WUIs	Not within 400m of WUIs	Intersecting previous fires	Not intersecting previous fires
Controlled Burn1
	2,848,958.1 
74.1%
	995,201.3 
25.9%	2,759,169.0 71.8%
	1,084,990.50 28.2%
Mechanical2
	46,115.0 
77.7%
	13,245.1 
22.3%	39,162.1 
66.0%
	20,198.0
34.0%
Both3
	4,856.2
99.9%	3.1
.1%	3,715.2
76.5%	1,144.1
23.5%
1Percentages are out of total controlled burn area on state DPAs
2Percentages are out of total mechanical treatment area on state DPAs
3Percentages are out of total area of burn and mechanical overlap on state DPAs

Total state DPA land occupied by WUIs was 55,913,917.6 km2 (44.9% of total state DPA land). As we expected, proportion of treatments close to WUIs were higher than those farther from WUIs. Controlled burns with area intersecting the 400m WUI buffer accounted for 74.1% of total controlled burns on state DPAs, while mechanical treatments close to WUIs accounted for 77.7% of total mechanical treatments on state DPAs (Table 1, Figure 1). Only .1% of total treated land near WUIs was both burned and mechanically treated. However, areas that were both burned and mechanically treated almost entirely occurred near WUIs, with 99.9% of burn and mechanical overlap intersecting with WUI buffers. 
  


As we expected, proportion of fuel treatments intersecting with areas of previous fire was greater than treatments not intersecting previous fires. Controlled burns intersecting with areas of previous fire took 71.8% of total burn area, and mechanical treatments intersecting with areas of previous fire took up 66% of total mechanical treatment area (Figure 2).

Many overlaps occurred between treatments that intersected with WUI buffers and treatments that intersected with previous fire sites. For instance, overlap accounted for 80% of mechanical treatments that intersected with WUI buffers. In other words, 80% of the total area of mechanical treatments that intersected with WUI buffers also intersected with previous fire sites. Likewise, 92.5% of mechanical treatments that intersected with previous fire sites also intersected with WUI buffers. For controlled burns, 74.5% that intersected with WUI buffers also intersected with previous fire sites, and 77% that intersected with previous fire sites also intersected with WUI buffers.*

## Discussion


Controlled burns accounted for far more land than did mechanical treatments. This may be because mechanical treatments are more expensive and require more labor to carry out in widespread areas. In addition, controlled burns became common practice before mechanical treatments and so were standardized prior to most mechanical methods (Williams 2005).

Higher proportions of controlled burns and mechanical treatments were present near WUIs, because residential areas are prioritized for citizen safety. Mechanical treatments in particular are common close to WUIs because of safety policies. According to Cal Fire, both ‘fuel management zones’ and ‘defensible space’ are implemented in residential areas. Fuel management zones are defined as “areas, usually surrounding communities, where the natural vegetative cover is reduced in density…fuel ladders are greatly reduced, and overstory and understory vegetation is spatially separated so that a ground fire will not, under normal fire conditions, climb into the canopy and turn into a crown fire.”


Defensible space is similar but also encompasses firefighting strategy and accessibility in the event of a fire: “an area within the perimeter of a parcel, development, neighborhood, or community where basic wildland fire protection practices and measures are implemented, providing the key point of defense from an approaching wildfire, or defense against encroaching wildfires or escaping structure fires…The establishment and maintenance of emergency vehicle access, emergency water reserves, street names, building identification, and fuel modification measures characterize the area” (Cal Fire).

Higher proportions of fuel treatments were also present in sites of previous fires. This is likely because previous fires represent fire-prone zones where treatment is needed to prevent high-intensity, dangerous fires. Future mapping on whether fires continue in these areas despite fuel treatments will offer further information on whether fuel treatments need to be strategized differently, and potentially on the necessity of fuel treatments as opposed to increased funding for fire suppression.

The discussion on wildfires is complex and must take into account urban planning, fire-prone areas, vegetation type, and fire regimes, among other variables. Analysis of current fuel treatment methods at the state, local, and federal levels is necessary to further improve treatment effectiveness. The objective of this study was to gain understanding of what factors currently influence locations of fuel treatments on state DPAs. We found that WUIs and previous fire sites both significantly affect presence of fuel treatments. Future studies should further analyze vegetation’s effects on fuel treatment presence, and whether fires continue to burn at high intensity in areas that have been already treated.


## References
“Fuels Treatment.” 2012. Cal Fire. >calfire.ca.gov<
Hoover, K. 2017. Wildfire Management Funding: Background, Issues, and FY2018 Appropriations. Congressional Research Service.
Keeley, J. 2018. Lecture: The 2017 California Fires. Hixon Center for Sustainable Environmental Design, Harvey Mudd College.
Stephens, S.L., J.J. Moghaddas, C. Edminster, C.E. Fiedler, S. Haase, M. Harrington, J.E. Keeley, E.E. Knapp, J.D. McIver, K. Metlen, C.N. Skinner, and A. Youngblood. 2009. “Fire treatment effects on vegetation structure, fuels, and potential fire severity in western U.S. forests.” Ecological Applications 19(2): 305-320.
Williams, G.W. 2005. The USDA Forest Service: The First Century. United States Department of Agriculture.



*This is confusing me and it’s hard to explain. How do we account for overlap when we’re doing statistics?
Questions for further improvement: 
•	Should we show the maps? Or just create figures? And if we don’t show maps in results, should we show some in methods?
•	What are the most effective maps to display? I know the maps I put in weren’t that informative.
•	How do we account for differences in WUI/ non-WUI state land when calculating the percentage of treatment areas that are close to WUIs vs not close to WUIs/ do we need to account for that?
•	How can we conduct stronger analyses?
•	We couldn’t find a vegetation layer for California, but we know there has to be one…
