---
title: "Climate Change and Fires -- Is this a red herring or the alarm alarmists have been warning about?"
subtitle: "How do the average weather conditions change locally? What are the implications of climate change?"
author: "Environmental Analysis 30 Students, Pomona College"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
bibliography: skeleton.bib
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```
# 2018 Fire Season

After the late autumn fires of 2017, the notion of a fire season in California is at best questionable. Fire season is all year around. And when the summer arrived in 2018, the fire season was exceptional distructive again. The questions we address in these set of blogs, what is the cause of these intense fires?; what are some of the implications for the Earth's inhabitants?; and how can we managed wildfires better?


## Climate, Radiative Forcing, and Carbon Dioxide

Although the Earth's climate has been changing for hundreds of thousands, even millions and billions of years, even small changes to the Earth's average temperatures has significant implications for human activities. Climate change science can be extremely complex, but here are two well undertood proceses: 

1) Carbon dioxide (and other ``greenhouse gases'') trap heat and make Earth warmer than it would be otherwise.

2) Human activity such as the burning of fossil fuels (coal, oil, gas) is rapidly increasing the amount of carbon dioxide in Earth’s atmosphere.

Based on these two processes, we can draw the following conclusion:

We should expect the rising carbon dioxide concentration to warm our planet, with the warming becoming more severe as we add more carbon dioxide. But does this mean that we should also expect wildfires to increase as well?

## Wildfires, Public Health, Management

The EA30 class of the 2018 Fall, evaluate a range of questions associated with climate and fires. First, we some basic aspects of fire science, then we looked at some of the implications on human health. Finally, we reviewed numerous attempts to managed the landscape to reduce the risk of wildfires. 

## Fire Science


Fire we reviewed the scientific literature to evaluate the implications of climate change, fire science. Wildfires tend to reoccur based on characteristics of the vegetation, climate, and source of ignition. 



For example, , 

[Griffith Park by Virginia Paschal](F2018_Blogs/Paschal.html)

[Fire Suppression in Southwest Australia by Catherine Ward](F2018_Blogs/Ward.html)

[Fire and ET: Understanding the Fire and Hyrdrology by Hans](F2018_Blogs/Zhou.html)


[State vs. Federal Fuel Treatment Effectiveness in CA by William Stone](F2018_Blogs/Stone.html)

Although climate change is an factor, direct, human related impacts need to become a bigger part of the conversation. After reviewing fire patterns in Griffith Park, an urban park in Los Angeles County, Anam Mehta argues that XXX ([Mehta 2018](F2018_Blogs/Mehta.html)). 

## Public Health

One of the greatest health risk to residents not in immediate danger is smoke inhalation. For example, particulate matter (PM 2.5) can flucuate above safe levels long after a fire has been contained ([Zhong 2018](F2018_Blogs/Zhong.html)). Kania reports that fuel sources can have differential impacts on public health ([Kania](F2018_Blogs/Kania.html)), thus state public health officials should play a stronger role in vegetation management that improve both ecological and public health outcomes. 

Although we might expect hopsital admissions to vary based on demography, Mason Asoto did not have a relationship between X and X. However, [Gunasti](F2018_Blogs/Gunasti.html)

## Reducing Risk and WUIs

How various juristictions respond to manage vegetation to reduce the risk of wildfires depends on several factors. It's obvious that fire management should vary by region, but Das suggested that fire management tools used depend on how patterns land use. As summarized by [Scanlon (2018)](F2018_Blogs/Scanlon.html), a combination of prescribed fire and mechanical thinning may be the most effective way to reduce the fuel load in the years following the managament technique.

For example, [Wilk 2018](F2018_Blogs/Wilk.html) believes that the presence of WUIs and previous fire sites both significantly affect presence of fuel treatments.

Even in other states, WUIs also particularly challenging. For example, [Reyes-Salazar (2008)](F2018_Blogs/Reyes.html) describes how fire suppression and ponderosa pines have created extremely hazards conditions for 75% of the inhabitants of the state.



[Wildfire Techniques in Coastal Plains of N Florida by Kyle](F2018_Blogs/Lenhart-Wees.html)

[Location and Fuel Management by Maia](F2018_Blogs/Pauley.html)

[Fuel Mangagement in CA by Alex](F2018_Blogs/Dykens-Hodapp.html)

[Social and Economic Factors and Fire Related Hospitalizations by Mason](F2018_Blogs/Asoto.html)

[Prescribed Burning as a type of Fuel Treatment by Gabriel](F2018_Blogs/Das.html)

[? by Hans](F2018_Blogs/Zhou.html)




# Conclusions

In spite of dramatic news headlines, we cannot blame wildfires on climate change. There are however, proximal and distal explanations for the high costs and extensive areas damangaed. Land use and forest management plays a key role -- while climate change is more like a multiplier effect -- exascterbating an existing historic management mistakes and poor land use decisions. 


## Previous Projects

[Why Climate Change Will Affect You Personally?](Index_2017F.html)

[Climate Change and Logical Fallacies](Index_2017S.html)
